#+title: Amazon AWS Ubuntu
* Amazon AWS Ubuntu
  固定 IP は有料.

** ping
  - [[http://qiita.com/janus_wel/items/faac04f2ec2cdb50d074][ssh config を汚さずに Ansible で Vagrant ホストを扱う - Qiita]]

#+begin_src bash
mkdir -p ~/.emacs.d/playbook
cd ~/.emacs.d/playbook
echo '54.65.121.127' > hosts
#+end_src

   以下の作業はすべて,~/.emacs.d/playbook で実施.

   ansible.cfg ファイルを作成.

   #+begin_src text
   [defaults]
   hostfile = ./hosts
   remote_user = ubuntu
   private_key_file = ~/.ssh/archlinux.pem
   host_key_checking = False
   #+end_src

   ping する.

#+begin_src bash :results raw silent :export both 
ansible all -m ping -i hosts
#+end_src

#+begin_src bash :results raw :export both 
ansible all -i hosts -a 'uname -r'
#+end_src

#+RESULTS:
52.68.172.183 | success | rc=0 >>
3.13.0-48-generic

** ansible setting

#+begin_src yaml :tangle yes
---
- hosts: defaults
  sudo: yes
  vars:
    home_dir: /home/ubuntu
    emacs_dir: emacs
    dotfiles_dir: dotfiles
  tasks:
#+end_src

** initial tools
   - libncurses5-dev は tputs error 対策
   - gnutls-bin for el-get
   - texinfo for makeinfo

#+begin_src yaml :tangle yes
    - name: apt-get update
      command: apt-get update
    - name: apt-get install git
      apt: pkg=git
    - name: apt-get install build tools
      apt: pkg=build-essential,autoconf,automake,libncurses5-dev,gnutls-bin,texinfo
#+end_src

  いちど apt-get install emacs したあとに ビルドすればいいかも...

*** bookmarks
   - [[http://gihyo.jp/admin/serial/01/ubuntu-recipe/0235][第 235 回  Ubuntu 12.04 で Emacs 24.1 を使う:Ubuntu Weekly Recipe|gihyo.jp … 技術評論社]]
   - [[http://emacs.tsutomuonoda.com/emacs24-1-ubuntu-install/][Emacs24.1 を Ubuntu にインストールする | Emacs の elisp インストール・設定・使い方]]

* Install Emacs
** building and install emacs
  - [[http://qiita.com/seizans/items/f5f052aec1592c47767f][Ansible で git clone させる - Qiita]]

    make -j オブションをつけたら, メモリ枯渇で make が停止した.

#+begin_src yaml :tangle no
    - name: get emacs from git repository
      git: repo=git://git.savannah.gnu.org/emacs.git dest={{home_dir}}/{{emacs_dir}} accept_hostkey=yes
    - name: make emacs configure file
      command: ./autogen.sh chdir={{home_dir}}/{{emacs_dir}}
    - name: make emacs Makefile
      command: ./configure --prefix=/usr/local --without-makeinfo --with-x-toolkit=no --without-all chdir={{home_dir}}/{{emacs_dir}}
    - name: make emacs
      command: make chdir={{home_dir}}/{{emacs_dir}}
    - name: install emacs
      command: make install chdir={{home_dir}}/{{emacs_dir}}
#+end_src

** get emacs
   今は、ビルドしないで、リポジトリから取得することにする.

#+begin_src yaml :tangle yes
    - name: apt-get install emacs
      apt: pkg=emacs
#+end_src

* Setup dotfiles
** install dotfiles
#+begin_src yaml :tangle yes
    - name: clone dotfiles
      sudo: no
      git: repo=https://github.com/tsu-nera/dotfiles.git dest={{home_dir}}/{{dotfiles_dir}}
    - name: make lnlinks
      command: ./make_lnlink chdir={{home_dir}}/{{dotfiles_dir}}
      sudo: yes
      sudo_user: ubuntu
#+end_src

** install additinal tools for emacs
#+begin_src yaml :tangle yes
    - name: install additinal tools for pdf-tools
      apt: pkg=libpng-dev,libz-dev,libpoppler-glib-dev,libpoppler-private-dev 
    - name: install additinal tools for magit
      apt: pkg=texinfo
    - name: install additinal tools for org2blog
      apt: pkg=bzr
    - name: install additinal tools for exectable-find
      apt: pkg=mercurial
    - name: install additinal tools for cmigemo
      apt: pkg=cmigemo
    - name: install additinal tools for ag
      apt: pkg=silversearcher-ag
#+end_src

* boot emacs
#+begin_src yaml :tangle yes
    - name: boot emacs first 
      command: emacs --daemon
      sudo: yes
      sudo_user: ubuntu
    - name: reboot emacs
      command: emacsclient -e '(progn (defun yes-or-no-p (p) t) (kill-emacs))' && emacs --daemon
      command: emacs --daemon
      sudo: yes
#+end_src

* Bookmarks
  - [[http://answersforaws.com/episodes/2-ansible-and-aws/][Ansible and AWS - Answers for AWS]]
  - [[http://mosuke5.hateblo.jp/entry/2014/11/16/153223][Ansible, ソースインストールする際の Palybook の書き方 - Goldstine 研究所]]
