#!/bin/sh
# -*- mode: shell-script -*-
#
# tangle files with org-mode
# see: http://orgmode.org/manual/Batch-execution.html
#
DIR=`pwd`
FILE=""

for i in $@; do
    # tangle org to yaml
    emacs -Q --batch --eval "(progn
     (add-to-list 'load-path \"/usr/share/emacs/site-lisp/org\")
     (require 'org)(require 'ob)(require 'ob-tangle)
     (setq org-src-preserve-indentation t)
     (find-file (expand-file-name \"$i\" \"$DIR\"))
     (org-babel-tangle)
     (kill-buffer))" 2>&1 | grep tangled

    # execute ansible command to yml file
    string_filename=${i##*/}
    string_filename_without_extension=${string_filename%.*}
    string_path=${i%/*}

    if test $string_filename = $i ; then
	ansible-playbook ${string_filename_without_extension}.yaml -i hosts
    else
	ansible-playbook ${string_path}/${string_filename_without_extension}.yaml -i hosts
    fi
done
