
* Programming
  いろいろなプログラミング言語に関わる設定.

** Emacs as IDE 
   優れた IDE が備えるべき機能は以下
   - シンタックスハイライト/ インデント
     - major-mode
   - 検索・置換
     iedit, multiple-cursors, helm-ag, helm-swoop
   - タグジャンプ
     GNU Global ggtags
   - コード補間
     - auto-complete, yasnippet
   - エラーチェック
     - flycheck
   - リファクタリング
     emacs-refactor
   - インタープリタ・デバッカ
   - プロジェクト管理
     projectile
   - ドキュメント参照
     eldoc

  参考: [[http://www.wilfred.me.uk/blog/2015/03/19/adding-a-new-language-to-emacs/][Adding A New Language to Emacs | Wilfred Hughes :: Blog]]

** prog-mode
   programming のためのメジャーモード.
   - [[http://www.emacswiki.org/emacs/ProgMode][EmacsWiki: Prog Mode]]

* 閲覧
** imenus
   imenu の強化.
   - https://github.com/alezost/imenus.el

   なんか, 思うように動かないぞ.

#+begin_src emacs-lisp
(use-package imenus
  :disabled t
  :init
  (define-key prog-mode-map (kbd "C-c h") 'imenus-mode-buffers)
  (define-key imenus-minibuffer-map (kbd "C-c h") 'imenus-exit-to-helm-multi-swoop)
  :commands (imenus imenus-mode-buffers)
  :preface
  (defun imenus-helm-multi-swoop (buffers input)
    (helm-multi-swoop (replace-regexp-in-string "^.*|" "" input)
                      (mapcar 'buffer-name buffers)))
  (defun imenus-exit-to-helm-multi-swoop ()
    "Exit from imenu prompt; start `helm-multi-swoop' with the current input."
    (interactive)
    (setq imenus-exit-status 'helm-multi-swoop))
  :config
  (push '(helm-multi-swoop . imenus-helm-multi-swoop) imenus-actions))
#+end_src

** imenu-anywhare
  imenu の強化.
  - https://github.com/vspinu/imenu-anywhere

  複数バッファで imenu

#+begin_src emacs-lisp
(use-package imenu-anywhere
  :disabled t ;; 動かなくなっちゃった...
  :bind* ("C-c h" . helm-imenu-anywhere)
  :config
  (require 'imenu) 
  (setq ido-enable-flex-matching t)       ;あいまいマッチ
  (defun jcs-use-package ()
    (add-to-list 'imenu-generic-expression
                 '("Used Packages"
                   "\\(^\\s-*(use-package +\\)\\(\\_<.+\\_>\\)" 2)))
  (add-hook 'emacs-lisp-mode-hook #'jcs-use-package))
#+end_src

** origami
   A folding minor mode for Emacs 
   - https://github.com/gregsexton/origami.el
   - [[http://rubikitch.com/2015/01/03/origami/][elisp,Clojure,C 系言語で org-mode 風の折畳みをする| るびきち「日刊 Emacs」]]

#+begin_src emacs-lisp
(use-package origami
  :disabled t
  :init
  (add-hook 'view-mode-hook 'view-mode-hook--origami)
  ;; お試しで, C 言語で有効にしてみよう
  ;; (add-hook 'c-mode-common-hook 'origami-mode)
  :commands view-mode-hook--origami
  :config
  (define-minor-mode origami-view-mode
    "TAB に origami の折畳みを割り当てる"
    nil "折紙"
    '(("\C-i" . origami-cycle))
    (or origami-mode (origami-mode 1)))
  (defun origami-cycle (recursive)
    "origami の機能を org 風にまとめる"
    (interactive "P")
    (call-interactively
     (if recursive 'origami-toggle-all-nodes 'origami-toggle-node)))
  (defun view-mode-hook--origami ()
    (when (memq major-mode (mapcar 'car origami-parser-alist))
      (origami-view-mode (if view-mode 1 -1))))

  ;; indent と競合するなぁ. org-mode のようになってほしい.
  ;; (define-key origami-mode-map (kbd "C-i") 'origami-forward-toggle-node)
  (define-key origami-mode-map (kbd "TAB") 'origami-forward-toggle-node)
  (define-key origami-mode-map (kbd "<backtab>") 'origami-toggle-all-nodes))
#+end_src

** yafolding
   - https://github.com/zenozeng/yafolding.el
   インデントによる折りたたみ. 

   第一階層に関数がある場合はいいんだけど、
   クラスにかこまれて第二階層に関数かあるときは、機能しないかなぁ...

#+begin_src emacs-lisp
(use-package yafolding
  :disabled t
  :config
  (define-key yafolding-mode-map (kbd "<C-S-return>") nil)
  (define-key yafolding-mode-map (kbd "<C-M-return>") nil)
  (define-key yafolding-mode-map (kbd "<C-return>") nil)
  (define-key yafolding-mode-map (kbd "C-c <C-M-return>") 'yafolding-toggle-all)
  (define-key yafolding-mode-map (kbd "C-c <C-S-return>") 'yafolding-hide-parent-element)
  (define-key yafolding-mode-map (kbd "C-c <C-return>") 'yafolding-toggle-element)  
  (global-set-key (kbd "s-d y") 'yafolding-discover)
  (add-hook 'prog-mode-hook
            (lambda () (yafolding-mode))))
#+end_src

** minimap
   Sublime Text のようなミニマップ. ちょっと重い.

 #+begin_src emacs-lisp
(use-package minimap
  :config
  (setq minimap-window-location 'right)
  (setq minimap-minimum-width 15)
  (global-set-key (kbd "C-c n") 'minimap-mode))

  ;; (when (display-graphic-p)
  ;;   (use-package minimap)
  ;;   ;; enable minimap
  ;;   (global-set-key (kbd "C-c n") 'minimap-toggle)))
 #+end_src

** indent-guide
   縦線をインデントで表示する。
   - https://github.com/zk-phi/indent-guide

#+begin_src emacs-lisp
(use-package indent-guide
  :config
  (setq indent-guide-delay 0.1)
  (setq indent-guide-recursive nil)
  ;; (set-face-foreground 'indent-guide-face "cyan")
  (add-hook 'prog-mode-hook 'indent-guide-mode))
#+end_src

* 編集 (とくにプログラミング)
** electric-spacing
   演算子の前後にスペースを挿入. 
   かつては smart-operator といわれた.
   - https://github.com/xwl/electric-spacing

  必要に応じて追加していく.

  -> electric-operator に変更.

  #+begin_src emacs-lisp
(use-package electric-spacing
  :init
  (add-hook 'c-mode-common-hook #'electric-spacing-mode)
  (add-hook 'python-mode-hook #'electric-spacing-mode))
#+end_src

** electric-operator
   - http://rubikitch.com/2015/07/19/electric-operator/
   インストールしたらエラーしたので、ひとまずいれるのを止めた.

** インデントで垂直方向に揃える
   M-x align-regexp
   - [[http://postd.cc/why-i-vertically-align-my-code-and-you-should-too/][【翻訳】私がコーディングで垂直方向にそろえるインデントをとる理由 | POSTD]]

   これ便利.
   - [[http://stackoverflow.com/questions/3633120/emacs-hotkey-to-align-equal-signs][Emacs hotkey to align equal signs - Stack Overflow]]

#+begin_src emacs-lisp
(defun align-to-equals (begin end)
  "Align region to equal signs"
   (interactive "r")
   (align-regexp begin end "\\(\\s-*\\)=" 1 1 ))
(global-set-key (kbd "C-x a =") 'align-to-equals)
#+end_src

** aggressive-indent-mode
   賢い indent-mode
   - https://github.com/Malabarba/aggressive-indent-mode

   *names* に依存しているので, 
   require 'names してからインストールしないとおかしくなる.

#+begin_src emacs-lisp
(require 'names)
(use-package aggressive-indent
  :init
  ;;  (global-aggressive-indent-mode))
  (add-hook 'emacs-lisp-mode-hook #'aggressive-indent-mode)
  (add-hook 'lisp-mode-hook #'aggressive-indent-mode)
  (add-hook 'racket-mode-hook #'aggressive-indent-mode))
#+end_src

* 補完
** auto-complete
   自動補完を実現する elisp.

   github:
   - https://github.com/auto-complete/auto-complete

   wiki:
   - http://www.emacswiki.org/emacs/auto-complete-extension.el

   manuals:
   - http://cx4a.org/software/auto-complete/index.ja.html
   - http://cx4a.org/software/auto-complete/manual.ja.html

#+begin_src emacs-lisp
(use-package auto-complete
  :bind   ("M-/" . auto-complete)
  :config
  (require 'auto-complete-config)
  (ac-config-default)
  ;; グローバルで auto-complete を利用
  (global-auto-complete-mode t)

  ;; 追加メジャーモード
  ;; -> org-mode と auto-complete の共用はバクあり.
  (add-to-list 'ac-modes 'org-mode)
  (add-to-list 'ac-modes 'sml-mode)
  (add-to-list 'ac-modes 'racket-mode)
  (add-to-list 'ac-modes 'octave-mode)

  ;; メニュー表示を遅延
  ;; (setq ac-auto-show-menu 0.5)
  (setq ac-auto-show-menu t)

  ;; 高さは 20 まで.
  (setq ac-menu-height 20)

  ;; 色を変更
  ;; (set-face-background 'ac-candidate-face "lightgray")
  ;; (set-face-background 'ac-candidate-face "orange")
  ;; (set-face-underline 'ac-candidate-face "darkgray")
  ;; (set-face-background 'ac-selection-face "steelblue")

  ;; 補完候補が 1 つのときはそれを採用.
  (setq ac-dwim t)

  (setq ac-auto-start nil)         ; 補完の自動スタートは抑止.
  ;; (setq ac-auto-start 3)           ; 3 文字以上から補完スタート
  (setq ac-auto-show-menu 0.8)     ; 0.8 秒でメニュー表示
  (setq ac-use-comphist t)         ; 補完候補をソート
  (setq ac-candidate-limit nil)    ; 補完候補表示を無制限に

  (setq ac-use-menu-map t)

  ;; デフォルトは C-n or C-p
  ;; Ctrl ではなくて, Alt に割り当てる.
  (define-key ac-menu-map (kbd "M-n") 'ac-next)
  (define-key ac-menu-map (kbd "M-p") 'ac-previous)

  ;; ヘルプを表示
  (define-key ac-completing-map (kbd "M-h") 'ac-quick-help)
   #+end_src

*** 情報源登録  
   ac-sources リストの最後に append で追加するだけ.
   - 

#+begin_src emacs-lisp
  (setq ac-sources (append ac-sources '(ac-source-abbrev)))
  (setq ac-sources (append ac-sources '(ac-source-words-in-buffer)))
  (setq ac-sources (append ac-sources '(ac-source-words-in-same-mode-buffers)))
#+end_src

   情報源の作り方
   - http://dev.ariel-networks.com/wp/documents/aritcles/emacs/part10  
   - http://fukuyama.co/emacs-auto-complete

*** ac-helm
    helm インターフェースを利用する. これは多げさかな. .

#+begin_src emacs-lisp
(use-package ac-helm
  :disabled t
  :bind  ("C-:" . ac-complete-with-helm)
  :config
  (define-key ac-complete-mode-map (kbd "C-:") 'ac-complete-with-helm))
#+end_src

*** end of config
    #+begin_src emacs-lisp
    )
    #+end_src

* コンパイル
** quickrun
  コンパイルを実行. smart-compile よりいい??
  - https://github.com/syohex/emacs-quickrun

  C-u C-u quickrun で quickrun-compile-only
  -> 内部で M-x compile をりようしているため,
  エラー箇所にジャンプすることができる.

#+begin_src emacs-lisp
(use-package quickrun
  :bind ("C-c r" . quickrun)
  :config
  (push '("*quickrun*") popwin:special-display-config)
  (setq quickrun-timeout-seconds 20)

  ;; C++ は default で C++11 に対応させる
  (quickrun-add-command "c++/c1z"
                      '((:command . "g++")
                        (:exec    . ("%c -std=c++1z %o -o %e %s"
                                     "%e %a"))
                        (:remove  . ("%e")))
                      :default "c++")
)
#+end_src

** rake
   Interaction with rake command tool.
   - https://github.com/asok/rake

#+begin_src emacs-lisp
(use-package rake
  :config
  (eval-after-load 'ruby-mode
    '(define-key ruby-mode-map (kbd "C-!") 'rake))
  (setq rake-completion-system 'helm))
#+end_src

** helm-make
   - https://github.com/abo-abo/helm-make

   #+begin_src emacs-lisp
   (use-package helm-make)
   #+end_src

* プロジェクト管理
** projectile
   Project Interaction Library for Emacs.
   - https://github.com/bbatsov/projectile
   
   自動でプロジェクトのルートディレクトリを探して, 
   それ以下のファイルを見つけたり色々できる.
   - [[http://blog.en30.net/2014/10/20/development-environment.html][最近の開発環境: mjolnir, projectile, peco - blog.en30.net]]

   .projectile ファイルをマニュアルで作成することで,
   そのフォルダを Route Folder と認識出来る.(要 Emacs 再起動)

   以下で GTAGS を作成.
   - projectile-regenerate-tags

   Prefix key of Projectile is C-c p. Some notable features: 
   - Jump to any file in the project: C-c p f. 
   - Jump to any directory in the project: C-c p d. 
   - List buffers local to current project: C-c p b. 
   - Jump to recently visited files in project: C-c p e. 
   - Grep in project: C-c p g s 
   - Multi-occur in project buffers: C-c p o. 
   - Simple refactoring with text replace in current project: C-c p r. 
   - Switch visited projects (visited once an Projectile remembers): C-c p p. 

   Useful commands for working with C/C++ projects: 
   - Run compilation command at project root: C-c p c. By default, Projectile prompts the make command. 
   - Switch between .h and .c or .cpp: C-c p a. (便利!!)

   #+begin_src emacs-lisp
(use-package projectile
  :defer 20
  :config
  (projectile-global-mode)
  ;; windows indexing 高速化のおまじない.
  (when windows-p
    (setq projectile-indexing-method 'alien))

  ;; 大きいプロジェクトだと劇的に改善するらしい.
  (setq projectile-enable-caching t)
  
  ;; gtags があればそっちを
  ;; ggtags が必要.
  (when (executable-find "gtags")
    (setq projectile-tags-file-name "GTAGS")
    (setq projectile-tags-command "gtags")))
   #+end_src

** ibuffer-projectile
   - https://github.com/purcell/ibuffer-projectile

#+begin_src emacs-lisp
(use-package ibuffer-projectile
  :config
  (add-hook 'ibuffer-hook
            (lambda ()
              (ibuffer-projectile-set-filter-groups)
              (unless (eq ibuffer-sorting-mode 'alphabetic)
                (ibuffer-do-sort-by-alphabetic)))))
#+end_src

* タグジャンプ
** GNU global: gtags
   ソースタギングシステム.
    - [[http://www.gnu.org/software/global/global.html][GNU GLOBAL source code tagging system]]
    - C, C++, Yacc, Java, PHP4 and assembly

    Pygments を利用すると, もっと多言語に適用できる.
    - [[https://github.com/yoshizow/global-pygments-plugin][yoshizow/global-pygments-plugin]]
    - Awk, Dos batch, COBOL, C, C++, C#, Erlang, Fortran, 
    - Java, JavaScript, Lisp, Lua, Pascal, Perl, PHP, Python, 
    - Ruby, Matlab, OCaml, Scheme, Tcl, TeX, Verilog, Vhdl and Vim

   以下からダウンロード. Windows ようのバイナリあり.
   - [[http://www.gnu.org/software/global/download.html][Getting GLOBAL]]

*** Bookmarks
    - [[http://uguisu.skr.jp/Windows/gtags.html][GNU GLOBAL (gtags) ソースコードタグシステムの使い方]]
    - [[http://qiita.com/5t111111/items/c14ac68f762ce71a7760][Ruby - GNU GLOBAL への Pygments パーサー取り込みでソースコード読みが信じられないくらいに捗るはず - Qiita]]

*** Emacs と
   - [[http://namamugi2011.blog.fc2.com/blog-entry-42.html][GNU GLOBAL と emacs でコードリーディング | ぷろぐらま]]

#+begin_src emacs-lisp
;; (use-package gtags)
;; :bind
;; (("\M-t" . gtags-find-tag) ;関数の定義元へ
;;  ("\M-r" . gtags-find-rtag) ;関数の参照先へ
;;  ("\M-s" . gtags-find-symbol) ;変数の定義元/ 参照先へ
;;  ;; ("\M-f" . gtags-find-file) ;ファイルにジャンプ
;;  ("\M-," . gtags-pop-stack));前のバッ ファに戻る
;; )
;; :init	
;; (add-hook 'c-mode-common-hook
;;           '(lambda ()
;;              (gtags-mode 1)
;;              (gtags-make-complete-list))))
#+end_src

** ggtags
   GNU Global 

   projectile で必要.
   - https://github.com/leoliu/ggtags

#+begin_src emacs-lisp
(use-package ggtags
  :init
  (add-hook 'c-mode-common-hook
            (lambda ()
              (when (derived-mode-p 'c-mode 'c++-mode 'java-mode 'asm-mode)
                (ggtags-mode 1))))
  (add-hook 'clojure-mode-hook (lambda () (ggtags-mode 1)))
  
  :config
  ;; use helm
  (setq ggtags-completing-read-function nil)

  ;; use eldoc
  (setq-local eldoc-documentation-function #'ggtags-eldoc-function)

  ;; imenu
  (setq-local imenu-create-index-function #'ggtags-build-imenu-index)
  
  (define-key ggtags-mode-map (kbd "C-c g s") 'ggtags-find-other-symbol)
  (define-key ggtags-mode-map (kbd "C-c g h") 'ggtags-view-tag-history)
  (define-key ggtags-mode-map (kbd "C-c g r") 'ggtags-find-reference)
  (define-key ggtags-mode-map (kbd "C-c g f") 'ggtags-find-file)
  (define-key ggtags-mode-map (kbd "C-c g c") 'ggtags-create-tags)
  (define-key ggtags-mode-map (kbd "C-c g u") 'ggtags-update-tags)
  (define-key ggtags-mode-map (kbd "C-c g m") 'ggtags-find-tag-dwim)
  
  (define-key ggtags-mode-map (kbd "M-,") 'pop-tag-mark))
#+end_src

* エラーチェック
** flymake
   静的文法チェック.

   -> flycheck にだんだん移行する.

#+begin_src emacs-lisp
(use-package flymake
  :disabled t
;;  :bind (("M-p"  . flymake-goto-prev-error)
;;	 ("M-n"  . flymake-goto-next-error)
;;	 ("C-c d" . flymake-display-err-menu-for-current-line))
  :init
  (add-hook 'find-file-hook 'flymake-find-file-hook)
  (add-hook 'haskell-mode-hook (lambda () (flymake-mode t)))
;; (add-hook 'java-mode-hook '(lambda () (flymake-mode t)))
  (add-hook 'emacs-lisp-mode-hook
	    (function (lambda () (if buffer-file-name (flymake-mode t)))))
  :config
  ;; GUI の警告は表示しない
  (setq flymake-gui-warnings-enabled nil)
#+end_src

*** Java
    Java は flycheck 対応していない...

#+begin_src emacs-lisp
(defun my-java-flymake-init ()
  (list "javac" (list (flymake-init-create-temp-buffer-copy
                       'flymake-create-temp-with-folder-structure))))
(add-to-list 'flymake-allowed-file-name-masks '("\\.java$" my-java-flymake-init flymake-simple-cleanup))

(defun flymake-java-init ()
  (list "my-java-flymake-checks"
	(list (flymake-init-create-temp-buffer-copy
	       'flymake-create-temp-with-folder-structure))))

(add-to-list 'flymake-allowed-file-name-masks
	     '("\\.java$" flymake-java-init flymake-simple-cleanup))
#+end_src

*** C/C++ 
    flycheck を利用するので封印
#+begin_src emacs-lisp
;; (defun flymake-cc-init ()
;;   (let* ((temp-file   (flymake-init-create-temp-buffer-copy
;; 		       'flymake-create-temp-inplace))
;; 	 (local-file  (file-relative-name
;; 		       temp-file
;; 		       (file-name-directory buffer-file-name))))
;;     (list "g++" (list "-Wall" "-Wextra" "-fsyntax-only" local-file))))

;; (push '("\\.c$" flymake-cc-init) flymake-allowed-file-name-masks)
;; (push '("\\.cpp$" flymake-cc-init) flymake-allowed-file-name-masks)
#+end_src

*** Python
     flymake でエラーチェックを実施. 
   エラーチェックのエンジンに pyflakes を利用する.

   #+begin_src bash
   $ sudo pip install pyflakes
   #+end_src

   Emacswiki を参考に設定.
   - [[http://www.emacswiki.org/PythonProgrammingInEmacs][EmacsWiki: Python Programming In Emacs]]

   -> flycheck に移行.

#+begin_src emacs-lisp
;; (defun flymake-pyflakes-init ()
;;   (when (not (subsetp (list (current-buffer)) (tramp-list-remote-buffers)))
;;     (let* ((temp-file (flymake-init-create-temp-buffer-copy
;;         	       'flymake-create-temp-inplace))
;;            (local-file (file-relative-name
;;         		temp-file
;;         		(file-name-directory buffer-file-name))))
;;       (list "pyflakes" (list local-file)))))
;;  
;; (add-to-list 'flymake-allowed-file-name-masks
;;              '("\\.py$" flymake-pyflakes-init))
#+end_src

*** Emacs lisp
    - [[http://www.lunaport.net/blog/2010/02/windowsflymake-elisp-1.html][Windows でも手軽に flymake elisp (修正版) - るなぽブログ]]

#+begin_src emacs-lisp
(defun flymake-elisp-init ()
  (unless (string-match "^ " (buffer-name))
    (let* ((temp-file   (flymake-init-create-temp-buffer-copy
                         'flymake-create-temp-inplace))
           (local-file  (file-relative-name
                         temp-file
                         (file-name-directory buffer-file-name))))
      (list
       (expand-file-name invocation-name invocation-directory)
       (list
        "-Q" "--batch" "--eval"
        (prin1-to-string
         (quote
          (dolist (file command-line-args-left)
            (with-temp-buffer
              (insert-file-contents file)
              (emacs-lisp-mode)
              (let ((parse-sexp-ignore-comments t))
                (condition-case data
                    (scan-sexps (point-min) (point-max))
                  (scan-error
                   (goto-char (nth 2 data))
                   (princ (format "%s:%s: error: Unmatched bracket or quote\n"
                                  file (line-number-at-pos))))))))
          )
         )
        local-file)))))

(push '("\\.el$" flymake-elisp-init) flymake-allowed-file-name-masks)
#+end_src

*** End of flymake
#+begin_src emacs-lisp
)
#+end_src

** flycheck
   静的文法チェック. flymake の後継. flymake から乗り換えよう.
   - [[https://github.com/flycheck/flycheck][flycheck/flycheck]]
   - [[http://www.flycheck.org/en/latest/][Flycheck - Modern Emacs syntax checking ]]

   Default のサポート言語
   - [[http://www.flycheck.org/en/latest/guide/languages.html][Supported languages - Flycheck 0.23-cvs]]

*** Usage
    基本の使い方
    - C-c ! c (flycheck-buffer) 現在のバッファを検査
    - C-c ! C (flycheck-clear)  
    - C-c ! n (flycheck-next-error)
    - C-c ! p (flycheck-previous-error)
    - C-c ! l (flycheck-list-errors) 

    以下で checker を切り替える
    - C-c ! s

*** Configuration
    - [[http://qiita.com/senda-akiha/items/cddb02cfdbc0c8c7bc2b][Emacs - Flycheck でモダンなシンタックスチェック - Qiita]]
    
#+begin_src emacs-lisp
(use-package flycheck
  :init
  ;; 除外
  ;; http://emacs.stackexchange.com/questions/21042/disable-minor-mode-in-major-mode
  (setq flycheck-global-modes '(not org-mode))
  (add-hook 'after-init-hook #'global-flycheck-mode)
  :config
  (defun my/turn-on-flycheck-mode ()
    (flycheck-mode 1))
  (setq flycheck-highlighting-mode 'lines))
#+end_src

*** extensions
**** flycheck-pos-tip
     ポップアップで注意事項を表示する. 

**** flycheck-color-mode-line
     エラーがあればモードラインが光る. flycheck のサブモジュール.
     - https://github.com/flycheck/flycheck-color-mode-line

     光らないが, powerline のせいか?
     
  #+begin_src emacs-lisp
(use-package flycheck-color-mode-line
  :init
  (eval-after-load "flycheck"
    '(add-hook 'flycheck-mode-hook 'flycheck-color-mode-line-mode)))
  #+end_src

* リファクタリング
** emacs-refactor
   - https://github.com/chrisbarrett/emacs-refactor

#+begin_src emacs-lisp
(use-package emr
  :config
  (add-hook 'prog-mode-hook 'emr-initialize)
  (define-key prog-mode-map (kbd "M-RET") 'emr-show-refactor-menu))

#+end_src

** semantic mode
   意味を解釈した, セマンティックな解析をする.
   - [[http://www.gnu.org/software/emacs/manual/html_node/emacs/Semantic.html][Semantic - GNU Emacs Manual]]

#+begin_src emacs-lisp
(semantic-mode 1)
#+end_src

   semantic がうまく動かないときは, .emacs.d/ 配下にある 
   semanticdb を削除して, 再構築する.

* Debugger
** emacs-dbgr
   - https://github.com/rocky/emacs-dbgr
   - https://github.com/rocky/emacs-dbgr/wiki/how-to-use

#+begin_src emacs-lisp
(use-package realgud :disabled t)
#+end_src

* Utils
** ediff
   emacs よう diff ツール
   - http://www.emacswiki.org/emacs/EdiffMode

   vdiff に乗り換えてみる

   #+begin_src emacs-lisp
(use-package ediff
  :disabled t
  :config
  ;; コントロール用のバッファを同一フレーム内に表示
  (setq ediff-window-setup-function 'ediff-setup-windows-plain)
  ;; 縦に分割
  (setq ediff-split-window-function 'split-window-horizontally)
  ;; ウィンドウサイズによっては横分割
  (setq ediff-split-window-function (if (> (frame-width) 150)
					'split-window-horizontally
				      'split-window-vertically))
  )
#+end_src

** vdiff 
   diff tool like vimdiff
   - https://github.com/justbur/emacs-vdiff

#+begin_src emacs-lisp
(use-package vdiff
  :config
  (define-key vdiff-mode-map (kbd "C-c") vdiff-mode-prefix-map))
#+end_src

** tdd
   Test-Driven Development 用の Elisp??
   なんか, エラーしてもグリーンな気がする.

#+begin_src emacs-lisp
(use-package tdd :disabled t)
#+end_src

** smart-newline
   空気を読んでくれる newline
   - [[http://ainame.hateblo.jp/entry/2013/12/08/162032][smart-newline.el という拡張 #emacs - ainame の日記]]
   - https://github.com/ainame/smart-newline.el

   #+begin_src emacs-lisp
   (use-package smart-newline
     :init
     (define-key global-map (kbd "C-j") 'smart-newline))
   #+end_src

** cloc
   ステップカウンタ
   - https://github.com/cosmicexplorer/cloc-emacs

   cloc というプログラムを呼び出す.

#+begin_src emacs-lisp
(use-package cloc)
#+end_src

* git
** magit
   Emacs の Git Client.
   - https://github.com/magit/magit
   - http://qiita.com/takc923/items/c7a11ff30caedc4c5ba7

   チートシート
   - http://daemianmack.com/magit-cheatsheet.html

   #+begin_src emacs-lisp
(use-package magit
  :bind ("C-c m" . magit-status)
  :commands (magit magit-svn)
  :config
  (setq magit-git-executable "git")
  (setq magit-emacsclient-executable "emacsclient")
#+end_src

*** magit-log で時刻表示
    - [[http://rubikitch.com/2015/01/30/magit-time-format/][magit のログで, コミット日時を時刻で表示させる設定 | るびきち]]

#+begin_src emacs-lisp
(defvar magit-log-time-format "%y-%m-%d %H:%M")
(defun magit-format-duration--format-date (duration spec width)
  (format-time-string magit-log-time-format
                      (seconds-to-time (- (float-time) duration))))
(advice-add 'magit-format-duration :override
            'magit-format-duration--format-date)
(defun magit-log-margin-set-timeunit-width--fixed ()
  (setq magit-log-margin-timeunit-width 12))
(advice-add 'magit-log-margin-set-timeunit-width :override
            'magit-log-margin-set-timeunit-width--fixed)
(setq magit-log-margin-spec '(33 nil magit-duration-spec))
#+end_src

*** end of config
    #+begin_src emacs-lisp
    )
    #+end_src

** gist
  Emacs gist interface
  - https://github.com/defunkt/gist.el

#+begin_src emacs-lisp
(use-package gist
  :config
  (defun browse-gist ()
      (interactive)
      (browse-url "https://gist.github.com/tsu-nera")))
#+end_src

  helm-gist というのもあるけど, 使い方わからない.
  - https://github.com/emacs-helm/helm-gist/blob/master/helm-gist.el

** git-gutter
   前回分との差分が見えるツール
   - https://github.com/syohex/emacs-git-gutter

   いつも有効にすると遅いので, 必要なときに手動で有効に.(org-mode で遅い)

#+begin_src emacs-lisp
(use-package git-gutter)
  ;; (global-git-gutter-mode +1)
  ;; (git-gutter:linum-setup))
#+end_src
     
** github 関連
 #+begin_src emacs-lisp
;; git 管理のシンボリックリンクで質問されないためのおまじない.
;; 参考: http://openlab.dino.co.jp/2008/10/30/212934368.html
;;; avoid "Symbolic link to Git-controlled source file;; follow link? (yes or no)
(setq git-follow-symlinks t)
 #+end_src

** git-link
   現在の git-link を取得.
   - https://github.com/sshaw/git-link
   - http://rubikitch.com/2015/03/28/git-link/
   
#+begin_src emacs-lisp
(use-package git-link
  :commands (git-link git-link-commit))
#+end_src

** git-timemachine
   - https://github.com/pidu/git-timemachine

#+begin_src emacs-lisp
(use-package git-timemachine)
#+end_src

* svn
** vc-mode
   Emacs にはじめから入っている.
   - [[http://dev.ariel-networks.com/articles/emacs/part7/][「VC (バージョンコントロール) パッケージの基礎」 (菅原泰樹) - ありえるえりあ]]

   | key     | command                  | 説明                   | svn command |
   |---------+--------------------------+------------------------+-------------|
   | C-x v = | vc-diff                  | 差分を表示             | diff        |
   | C-x v l | vc-print-log             | 履歴を表示             | log         |
   | C-x v g | vc-annotate              | 注釈を表示             | blame       |
   | C-x v ~ | vc-revision-other-window | 過去のバージョンを表示 | cat         |
   | C-x v + | vc-update                | 更新                   | update      |
   | C-x v v | vc-next-action           | コミット               | commit      |
   | C-x v i | vc-register              | ファイルの追加         | add         |
   | C-x v u | vc-revert                | 修正の破棄             | revert      |
   | C-x v d | vc-dir                   | 状態の表示             | status      |
   |         | ediff-revision           | Ediff で差分を表示     |             |

   vc-annotate がすごくいい.
   - [[http://d.hatena.ne.jp/naoya/20080404/1207294998][Emacs の vc-annotate - naoya のはてなダイアリー]]
   - [[http://blog.kyanny.me/entry/2014/08/16/022311][vc-git の vc-annotate をコンパクトな見た目にする - @kyanny's blog]] 

#+begin_src emacs-lisp
(defadvice vc-git-annotate-command (around vc-git-annotate-command activate)
  "suppress relative path of file from git blame output"
  (let ((name (file-relative-name file)))
    (vc-git-command buf 'async nil "blame" "--date=iso" rev "--" name)))
#+end_src

** speedup
  - [[http://stackoverflow.com/questions/8837712/emacs-creates-buffers-very-slowly][windows - Emacs creates buffers very slowly - Stack Overflow]]

#+begin_src emacs-lisp
(remove-hook 'find-file-hooks 'vc-find-file-hook)
#+end_src

*** vc git が遅くなる??
  - [[http://emacs.1067599.n5.nabble.com/slow-opening-of-files-in-git-directories-in-windows-td187276.html][Emacs - Dev - slow opening of files in git directories in windows]]

#+begin_src emacs-lisp
(setq vc-handled-backends nil)
#+end_src

** browse-at-remote
   - https://github.com/rmuslimov/browse-at-remote

#+begin_src emacs-lisp
(use-package browse-at-remote
  :bind "C-c g g")
#+end_src

* Tips
** code review
   - http://www.blogbyben.com/2015/04/the-joy-of-elisp-powered-code-review.html

   #+begin_src emacs-lisp
(defun chomp (str)
  "..."
  (let ((s (if (symbolp str) (symbol-name str) str)))
    (save-excursion
      (while (and
              (not (null (string-match "^\\( \\|\f\\|\t\\|\n\\)" s)))
              (> (length s) (string-match "^\\( \\|\f\\|\t\\|\n\\)" s)))
        (setq s (replace-match "" t nil s)))
      (while (and
              (not (null (string-match "\\( \\|\f\\|\t\\|\n\\)$" s)))
              (> (length s) (string-match "\\( \\|\f\\|\t\\|\n\\)$" s)))
        (setq s (replace-match "" t nil s))))
    s))

(defun code-review-region (beg end)
  (interactive "r")
  (let* ((text (chomp (buffer-substring-no-properties beg end)))
         (line-number (line-number-at-pos))
         (file (buffer-file-name))
         (path (replace-regexp-in-string "^.*branches/" ""
                                         (replace-regexp-in-string 
                                          "^.*trunk/" "" file))))
     (with-temp-buffer
       (insert text)
       (goto-char (point-min))
       (while (re-search-forward "^" nil t)
         (replace-match "| " nil nil))
       (goto-char (point-min))
       (insert (format "+---[%s:%s]\n" path line-number))
       (goto-char (point-max))
       (insert "\n+---\n")
       (kill-region (point-min) (point-max)))))
#+end_src

* Bookmarks
