* R
  統計解析言語 R について. 

** ESS
    Emacs を統計用 IDE にするツール. デファクトスタンダードと言える.

    - Official: [[http://ess.r-project.org/][ESS - Emacs Speaks Statistics]]
    - github: https://github.com/emacs-ess/ESS
    - メチャクチャ詳しい: [[http://www.okada.jp.org/RWiki/?ESS][ESS - RjpWiki]]
    - [[http://www.emacswiki.org/emacs/EmacsSpeaksStatistics][EmacsWiki: Emacs Speaks Statistics]]
    - [[http://d.hatena.ne.jp/a_bicky/20120415/1334490586][ESS で快適 R ライフ ~設定編~(2012 年度版) - あらびき日記]]
    - [[http://d.hatena.ne.jp/a_bicky/20120422/1335086814][ESS で快適 R ライフ ~操作編~(2012 年度版) - あらびき日記]]

*** Install
**** arch linux

     yaourt でインストール. yaourt -S emacs-ess.
     emacs 自体は独自のものを利用しているため,
     ビルドファイルで Emacs をコメントアウトした.

**** windows
     結構めんどくさいかも...
     - [[http://ess.r-project.org/index.php?Section=download][ESS - Emacs Speaks Statistics]]
     - [[http://d.hatena.ne.jp/Rion778/20100920/1284919925][Emacs + ESS で R (for Windows users) - もうカツ丼でいいよな]]

     github から直接最新版を取得して, 適当な場所に配置. 
     load-path を通す.
     - https://github.com/emacs-ess/ESS

*** config
     起動は M-x R.

#+begin_src emacs-lisp
(use-package ess-site
  :load-path ("/usr/share/emacs/site-lisp/ess" "c:/app/ess/lisp")
  :if (locate-library "ess-site")
  :commands R-mode
  :init
  (setq auto-mode-alist
	(cons (cons "\\.[rR]$" 'R-mode) auto-mode-alist))
  ;; うまく有効にならないので, hook を追加してみる.
  (add-hook 'R-mode-hook  '(lambda ()
			     (auto-complete-mode)
			     (setq ess-use-auto-complete t)))
  :config
  ;; R 起動時にワーキングディレクトリを訊ねない
  (setq ess-ask-for-ess-directory nil)
#+end_src

** ESS Auto-complete
   R 言語の入力自動補完をするために, auto-complete を利用する.
   - [[http://www.emacswiki.org/emacs/ESSAuto-complete][EmacsWiki: ESSAuto-complete]]   

   ac-R.el はふるいっぽい.
   - [[http://www.emacswiki.org/emacs/AutoCompleteSources#toc2][EmacsWiki: Auto Complete Sources]]
   - [[http://stackoverflow.com/questions/4682459/emacs-autocomplete-mode-extension-for-ess-and-r][Emacs autocomplete-mode extension for ESS and R - Stack Overflow]]
   - [[http://kozo2.hatenablog.com/entry/2012/04/14/050121][ESS の auto-complete を試す - kozo2's blog]]

#+begin_src emacs-lisp
(setq ess-use-auto-complete t)
;; (setq ess-use-auto-complete 'script-only)
#+end_src

** ESS R Data View
   データの中身がみれる.
   - [[http://sheephead.homelinux.org/2013/05/10/7019/][R のデータビューワ ess-R-data-view.el というのを作りました - sheephead]]
   - https://github.com/myuhe/ess-R-data-view.el

   no ESS process is associated with ... と出てきたら, C-c C-s で

#+begin_src emacs-lisp
(use-package ess-R-data-view
  :config
  ;; (define-key ess-mode-map (kbd "C-c v") 'ess-R-dv-ctable)
  (define-key ess-mode-map (kbd "C-c v") 'ess-R-dv-pprint)
  )
#+end_src

   popwin と組み合わせると便利.
   
** ess-R-object-popup
  オブジェクトの中身をポップアップで表示.
  - https://github.com/myuhe/ess-R-object-popup.el
  - [[http://sheephead.homelinux.org/2010/03/02/1807/][popup.el を使って R オブジェクトの情報を popup する ess-R-object-popup.el - sheephead]]

#+begin_src emacs-lisp
  (use-package ess-R-object-popup
    :config
    (define-key ess-mode-map "\C-c\C-g" 'ess-R-object-popup)
    )
#+end_src

  gist 版は古いようだ.
  - https://gist.github.com/myuhe/318365

  no ESS process is associated with this buffer というエラー
  がでたら C-c C-s を叩く.
  - [[http://stackoverflow.com/questions/13930713/ess-rdired-i-get-this-error-no-ess-process-is-associated-with-this-buffer-now][r - ess-rdired: I get this error "no ESS process is associated with this buffer now" - Stack Overflow]]

** helm-R
  helm インタフェースで 関数のヘルプをひくことができる.
  - [[http://sheephead.homelinux.org/2010/05/24/1846/][R のための anything インターフェイス, anything-R.el を作った. - sheephead]]
  - https://github.com/emacs-helm/helm-R

#+begin_src emacs-lisp
  (use-package helm-R
    :config
    (define-key ess-mode-map "\C-ch" 'helm-for-R)
    (define-key inferior-ess-mode-map "\C-ch" 'helm-for-R)
    )
#+end_src

** org-babel-R
   org-mode で R を利用する.
   - [[http://orgmode.org/worg/org-contrib/babel/languages/ob-doc-R.html][R Source Code Blocks in Org Mode]]
   - [[http://sheephead.homelinux.org/2010/05/25/1868/][Emacs 上のマルチな実行環境, Org-babel - sheephead]]
   - https://github.com/erikriverson/org-mode-R-tutorial/blob/master/org-mode-R-tutorial.org

   R 言語と org-mode で Reproducible Research を.
   - https://github.com/vikasrawal/orgpaper/blob/master/orgpapers.org

   設定は, org-mode.org に移動.

*** template
    ファイル名とサイズを指定する.
   - [[http://d.hatena.ne.jp/tamura70/20100315/org][Emacs org-mode を使ってみる: (40) org-babel-R を使う 1/2 - 屯遁のパズルとプログラミングの日記]]
   - [[http://d.hatena.ne.jp/tamura70/20100316/org][Emacs org-mode を使ってみる: (41) org-babel-R を使う 2/2 - 屯遁のパズルとプログラミングの日記]]

#+BEGIN_SRC R :file hogehoge.png :width 400 :height 400 :results graphics 
  plot (matrix (rnorm (100), ncol=2), type="l")
#+END_SRC

  C-c C-c で eval.

** R-autoyas
   Automatically create yasnippets for R
   - https://github.com/mlf176f2/r-autoyas.el

#+begin_src emacs-lisp
(use-package r-autoyas
  :commands r-autoyas-ess-activate
  :init
  (add-hook 'ess-mode-hook 'r-autoyas-ess-activate))
#+end_src

** End of ESS Config
#+begin_src emacs-lisp
)
#+end_src


* Markdown Mode
  Major mode for editing markdown
  - http://jblevins.org/projects/markdown-mode/markdown-modee.el

  #+begin_src emacs-lisp
(use-package markdown-mode
  :commands markdown-mode
  :mode ("\\.md$" . markdown-mode)
  :init
  (defun markdown-unset-tab ()
    "markdown-mode-hook"
    (interactive)
    (define-key markdown-mode-map (kbd "<tab>") nil))
  (add-hook 'markdown-mode-hook '(lambda () (markdown-unset-tab)))
  (add-hook 'poly-markdown+r-mode-hook '(lambda () (markdown-unset-tab))))
#+end_src

** realtime-preview
   Markdown を eww でリアルタイムプレビューする.
   - https://github.com/niku/realtime-preview.el
   - [[http://niku.name/articles/2014/11/17/Emacs%E3%81%A0%E3%81%91%E3%81%A7Markdown%E3%81%AE%E3%83%AA%E3%82%A2%E3%83%AB%E3%82%BF%E3%82%A4%E3%83%A0%E3%83%97%E3%83%AC%E3%83%93%E3%83%A5%E3%83%BC%E3%82%92%E3%81%99%E3%82%8B][2014/11/17/Emacs だけで Markdown のリアルタイムプレビューをする ]]

#+begin_src language
gem install redcarpet
#+end_src

重すぎて使えない...

#+begin_src emacs-lisp
(use-package realtime-preview.el :disabled t)
#+end_src

** moz-markdwon-viewer
   - [[http://d.hatena.ne.jp/syohex/20121122/1353598333][Emacs + MozRepl + Github Markdown API を使った Markdown Viewer - Life is very short]]
   - https://github.com/syohex/emacs-moz-markdown-viewer

#+begin_src emacs-lisp
(use-package moz-markdown-viewer
  :config
  (eval-after-load 'markdown-mode
    '(define-key markdown-mode-map (kbd "C-c C-r") 'moz-markdown-viewer:render)))
#+end_src

* csv-mode
  csv のためのモード.
  - https://github.com/emacsmirror/csv-mode
  - http://www.emacswiki.org/emacs/CsvMode

  powerline が有効だとエラーする.
  csv を使いたいときは, powerline を無効にすること.

  - https://github.com/emacsmirror/csv-mode/pull/2
  
#+begin_src emacs-lisp
(use-package csv-mode)
#+end_src

* polymode
  複数のモードを共存させる. これを利用して R と markdown を共存.
  - [[http://johnstantongeddes.org/open%20science/2014/03/26/Rmd-polymode.html][Using ESS with .Rmd files | John Stanton-Geddes]]
  - [[http://stackoverflow.com/questions/16567348/knitr-markdown-highlighting-in-emacs][r - knitr Markdown highlighting in Emacs? - Stack Overflow]]
  - https://github.com/vspinu/polymode

  eieio-constructor が undef なので封印.
    
#+begin_src emacs-lisp
;; (use-package poly-markdown
;;   :init
;;   ;; MARKDOWN
;;   (add-to-list 'auto-mode-alist '("\\.md" . poly-markdown-mode)))
;;  
;; (use-package poly-R
;;   :init
;;   ;; R modes
;;   (add-to-list 'auto-mode-alist '("\\.Snw" . poly-noweb+r-mode))
;;   (add-to-list 'auto-mode-alist '("\\.Rnw" . poly-noweb+r-mode))
;;   (add-to-list 'auto-mode-alist '("\\.Rmd" . poly-markdown+r-mode)))
#+end_src

* R Markdown
  ess-swv-knit で Rmd を md に変換できる.
  - [[http://d.hatena.ne.jp/a_bicky/20140221/1392941055#][R でレポートを作成するのに knitr が超便利 - あらびき日記]]

  html に変換するには, 以下の方法がある.
  - https://twitter.com/braingrasper/status/436689893624778752
  - [[http://roughtheory.com/posts/ess-rmarkdown.html][Using R Markdown in Emacs]]

#+begin_src emacs-lisp
(defun rmarkdown-to-html ()
  (interactive)
  "Run knitr::knit2html on the current file"
  "https://gist.github.com/kohske/9128031"
  (shell-command
   (format "Rscript -e \"knitr::knit2html ('%s')\""
	   (shell-quote-argument (buffer-file-name)))))

;; do this in R process
;; library (rmarkdown); render ("file_name.Rmd")

(defun ess-rmarkdown ()
  (interactive)
  "Compile R markdown (.Rmd). Should work for any output type."
  "http://roughtheory.com/posts/ess-rmarkdown.html"
  ; Check if attached R-session
  (condition-case nil
      (ess-get-process)
    (error 
     (ess-switch-process)))
  (let* ((rmd-buf (current-buffer)))
    (save-excursion
      (let* ((sprocess (ess-get-process ess-current-process-name))
	     (sbuffer (process-buffer sprocess))
	     (buf-coding (symbol-name buffer-file-coding-system))
	     (R-cmd
	      (format "library (rmarkdown); rmarkdown::render (\"%s\")"
		      buffer-file-name)))
	(message "Running rmarkdown on %s" buffer-file-name)
	(ess-execute R-cmd 'buffer nil nil)
	(switch-to-buffer rmd-buf)
	(ess-show-buffer (buffer-name sbuffer) nil)))))

;; (define-key polymode-mode-map "\M-ns" 'ess-rmarkdown)
#+end_src
