* Minor Language
  マイナーランゲージのマイナーモード. 量が増えてきたら別ベージに独立.

* Oz
  multi-paradium language

  導入方法:
  - http://www.eecs.ucf.edu/~leavens/ComS541Fall06/running_oz.shtml
    
  文法:
  - [[https://mozart.github.io/mozart-v1/doc-1.4.0/base/index.html][The Oz Base Environment]]
    
#+begin_src emacs-lisp 
;;; Oz program mode with Mozart/Oz.
;;; You have to arrange for the Oz-related emacs lisp (.el) files
;;; to be in emacs's load-path, for its bin directory to be in the PATH,
;;; and for the OZHOME environment variable to be set properly.
(use-package oz
  :commands (run-oz oz-mode oz-gump-mode oz-new-buffer)
  :mode (("\\.oz$'" . oz-mode) ("\\.ozg$'" . oz-gump-mode))
  :init
  (add-hook 'oz-mode-hook
	    (lambda ()
	      (define-key oz-mode-map "\C-c\C-b" 'oz-feed-buffer)
	      (define-key oz-mode-map "\C-c\C-l" 'oz-feed-line)
	      (define-key oz-mode-map "\C-c\C-r" 'oz-feed-region)
	      ))
  :config
  ;; indent を 3 から 2 へ変更
  (setq oz-indent-chars 2)

  (eval-after-load "auto-complete"
  '(add-to-list 'ac-modes 'oz-mode))
  )
#+end_src

* Cool
  - https://github.com/markxnelson/cool-mode
  
#+begin_src emacs-lisp
(use-package cool-mode
  :mode "\\.cl$")
#+end_src

* VBA 
** vbasense
#+begin_src emacs-lisp
(use-package vbasense
  :if windows-p
  :commands vbasense
  :mode "\\.\\(vbs\\|vb\\|wsf\\|frm\\|bas\\|cls\\)$"
  :config
  (setq vbasense-popup-help-key "C-:")
  (setq vbasense-jump-to-definition-key "C->")

  ;;(customize-group "vbasense")
  ;; use recommmended setting
  (vbasense-config-default)

  ;; (custom-set-variables
  ;; '(vbasense-tli-files "C:/Program Files/Microsoft Office/OFFICE11/EXCEL.EXE"))
  ;; "c:/Program Files/Common Files/Microsoft Shared/VBA/VBA6/VBE6.DLL"
  ;; "c:/Program Files/Common Files/Microsoft Shared/VBA/VBA6/VBE6EXT.OLB"
  ;; "c:/Program Files/Common Files/Microsoft Shared/OFFICE11/MSO.DLL"
  ;; "c:/WINDOWS/system32/stdole2.tlb")
  ;; 	   )
  )
#+end_src

** visual-basic-mode

#+begin_src emacs-lisp
(use-package visual-basic-mode
  :commands visual-line-mode
  :mode "\\.\\(vbs\\|vb\\|wsf\\|frm\\|bas\\|cls\\)$"
  )
#+end_src

* Assembly Language
  アセンブリ言語.
  - [[http://www.emacswiki.org/emacs/AssemblyProgramming][EmacsWiki: Assembly Programming]]

  asm-mode が標準添付.

* DSL
** yaml-mode
 #+begin_src emacs-lisp
(use-package yaml-mode :commands yaml-mode)
 #+end_src

** rst-mode
   Major mode for editing Restructured Text

 #+begin_src emacs-lisp 
(use-package rst
  :commands rst-mode
  :mode (("\\.rst$" . rst-mode) ("\\.rest$" . rst-mode))
  :config
  ;; RST モードを見やすくする.
  (setq frame-background-mode 'dark)
  
  ;; 全部スペースでインデントしましょう
  ;; (add-hook 'rst-mode-hook '(lambda () (setq indent-tabs-mode nil)))
)
 #+end_src

** Plant UML Mode
   Major mode for editing PlantUML.
   - [[http://plantuml.sourceforge.net/emacs.html][PlantUML]]
   - [[http://futurismo.biz/archives/2305][Emacs から PlantUML を便利につかう方法 | Futurismo]]

   #+begin_src emacs-lisp
(use-package plantuml-mode
  :if linux-p
  :commands plantuml-mode
  :mode (("\\.puml$" . plantuml-mode)
	 ("\\.plantuml$" . plantuml-mode))
  :config
  (setq plantuml-jar-path "/usr/local/bin/plantuml.jar")
  )
 #+end_src

** ansible
   - https://github.com/k1LoW/emacs-ansible
   - [[http://k1low.hatenablog.com/entry/2014/05/27/231132][Ansible の Playbook を書くときに便利になるかもしれない ansible.el を書いてみた - Copy/Cut/Paste/Hatena]]

   submodule で ansible repo を clone していて,
   重かったのでいったん休止.

 #+begin_src emacs-lisp
(use-package ansible
  :disabled t
  :commands ansible)
 #+end_src

* wiki
** textile-mode
   Redmine wiki の記述用.
   - [[http://dev.nozav.org/textile-mode.html][Textile-mode · dev.nozav.org]]

   el-get じゃとれないかも
   - http://dev.nozav.org/scripts/textile-mode.el.
  
 #+begin_src emacs-lisp
(use-package textile-mode
  :mode ("\\.textile$" . textile-mode))
 #+end_src

** pukiwiki-mode
   pukiwiki-mode は minor-mode のみ使用する. 
   firefox や chrome の Edit 機能から, Emacs を起動する.

   - [[http://www.bookshelf.jp/pukiwiki/pukiwiki.php?%A5%A2%A5%A4%A5%C7%A5%A2%BD%B8%2Fpukiwiki-mode][アイデア集/pukiwiki-mode - Meadow memo]]
   - pukiwiki-mode.el  http://www.bookshelf.jp/elc/pukiwiki-mode.el
   - http.el http://tdiary.cvs.sourceforge.net/tdiary/contrib/util/tdiary-mode/
   - [[http://rmecab.jp/wiki/index.php?Wiki_pukiwiki-mode%A4%F2%C6%B3%C6%FE][Wiki_pukiwiki-mode を導入 - R と Linux と...]]

#+begin_src emacs-lisp
;; (use-package pukiwiki-mode)
#+end_src
* hdl
  Hardware Descripton Language.

#+begin_src emacs-lisp
;;(use-package vhdl-mode
;;   :mode "\\.hdl$")
#+end_src

* SML
  - http://www.smlnj.org/doc/Emacs/sml-mode.html
  - http://www.iro.umontreal.ca/~monnier/elisp/

#+begin_src emacs-lisp :tangle yes
(autoload 'sml-mode "sml-mode" "Major mode for editing SML." t)
(autoload 'run-sml "sml-proc" "Run an inferior SML process." t)
(add-to-list 'auto-mode-alist '("\\.\\(sml\\|sig\\)\\'" . sml-mode))
#+end_src

** flycheck-sml
   - https://github.com/creichert/flycheck-sml

     - use-package が動かない。
     - mlton のインストールが必要らしい
     
#+begin_src emacs-lisp
(require 'flycheck-sml)
#+end_src

* Othres
** conkeror
   
 #+begin_src emacs-lisp
(use-package conkeror-minor-mode :commands conkeror-minor-mode)
 #+end_src
 
** mql

#+begin_src emacs-lisp
(use-package mql-mode)
#+end_src
** fish-mode
   Emacs major mode for fish shell scripts.
   - https://github.com/wwwjfy/emacs-fish
   
#+begin_src emacs-lisp
(use-package fish-mode)
#+end_src

