* Minor Language
  マイナーランゲージのマイナーモード. 量が増えてきたら別ベージに独立.

* Oz
  multi-paradium language

  導入方法:
  - http://www.eecs.ucf.edu/~leavens/ComS541Fall06/running_oz.shtml
    
  文法:
  - [[https://mozart.github.io/mozart-v1/doc-1.4.0/base/index.html][The Oz Base Environment]]
    
#+begin_src emacs-lisp 
;;; Oz program mode with Mozart/Oz.
;;; You have to arrange for the Oz-related emacs lisp (.el) files
;;; to be in emacs's load-path, for its bin directory to be in the PATH,
;;; and for the OZHOME environment variable to be set properly.
(use-package oz
  :commands (run-oz oz-mode oz-gump-mode oz-new-buffer)
  :mode (("\\.oz$'" . oz-mode) ("\\.ozg$'" . oz-gump-mode))
  :init
  (add-hook 'oz-mode-hook
	    (lambda ()
	      (define-key oz-mode-map "\C-c\C-b" 'oz-feed-buffer)
	      (define-key oz-mode-map "\C-c\C-l" 'oz-feed-line)
	      (define-key oz-mode-map "\C-c\C-r" 'oz-feed-region)
	      ))
  :config
  ;; indent を 3 から 2 へ変更
  (setq oz-indent-chars 2)

  (eval-after-load "auto-complete"
  '(add-to-list 'ac-modes 'oz-mode))
  )
#+end_src

* Cool
  
#+begin_src emacs-lisp
(use-package cool-mode
  :mode "\\.cl$")
#+end_src

* VBA 
** vbasense
#+begin_src emacs-lisp
(use-package vbasense
  :if windows-p
  :commands vbasense
  :mode "\\.\\(vbs\\|vb\\|wsf\\|frm\\|bas\\|cls\\)$"
  :config
  (setq vbasense-popup-help-key "C-:")
  (setq vbasense-jump-to-definition-key "C->")

  ;;(customize-group "vbasense")
  ;; use recommmended setting
  (vbasense-config-default)

  ;; (custom-set-variables
  ;; '(vbasense-tli-files "C:/Program Files/Microsoft Office/OFFICE11/EXCEL.EXE"))
  ;; "c:/Program Files/Common Files/Microsoft Shared/VBA/VBA6/VBE6.DLL"
  ;; "c:/Program Files/Common Files/Microsoft Shared/VBA/VBA6/VBE6EXT.OLB"
  ;; "c:/Program Files/Common Files/Microsoft Shared/OFFICE11/MSO.DLL"
  ;; "c:/WINDOWS/system32/stdole2.tlb")
  ;; 	   )
  )
#+end_src

** visual-basic-mode

#+begin_src emacs-lisp
(use-package visual-basic-mode
  :commands visual-line-mode
  :mode "\\.\\(vbs\\|vb\\|wsf\\|frm\\|bas\\|cls\\)$"
  )
#+end_src

* Scala
** scala-mode2

#+begin_src emacs-lisp 
;; Scala Mode 2
(use-package scala-mode2
  :commands scala-mode2
  :mode (("\\.scala$" . scala-mode) ("\\.sbt$" . scala-mode))
)
#+end_src

** ensime
   ENhanced Scala Interaction Mode for Emacs.
   
   This step causes the ensime-mode to be started whenever
   scala-mode is started for a buffer. You may have to customize this step
   if you're not using the standard scala mode.

#+begin_src emacs-lisp
(use-package ensime
  :commands ensime-scala-mode
  :init
  (add-hook 'scala-mode-hook 'ensime-scala-mode-hook)
)
#+end_src

** sbt mode
    - https://github.com/hvesalai/sbt-mode

#+begin_src emacs-lisp 
(use-package sbt-mode
  :init
  (add-hook 'sbt-mode-hook '(lambda ()
  ;; compilation-skip-threshold tells the compilation minor-mode
  ;; which type of compiler output can be skipped. 1 = skip info
  ;; 2 = skip info and warnings.
  (setq compilation-skip-threshold 1)

  ;; Bind C-a to 'comint-bol when in sbt-mode. This will move the
  ;; cursor to just after prompt.
  (local-set-key (kbd "C-a") 'comint-bol)

  ;; Bind M-RET to 'comint-accumulate. This will allow you to add
  ;; more than one line to scala console prompt before sending it
  ;; for interpretation. It will keep your command history cleaner.
  (local-set-key (kbd "M-RET") 'comint-accumulate)
  ))

  (add-hook 'scala-mode-hook '(lambda ()
   ;; sbt-find-definitions is a command that tries to find (with grep)
   ;; the definition of the thing at point.
   (local-set-key (kbd "M-.") 'sbt-find-definitions)

   ;; use sbt-run-previous-command to re-compile your code after changes
   (local-set-key (kbd "C-x '") 'sbt-run-previous-command)
   ))
)
#+end_src

** scala-electric-mode
#+begin_src emacs-lisp
;; (use-package scala-mode-feature-electric)
;; (add-hook 'scala-mode-hook
;;      (lambda ()
;;        (scala-electric-mode)))
#+end_src

* Assembly Language
  アセンブリ言語.
  - [[http://www.emacswiki.org/emacs/AssemblyProgramming][EmacsWiki: Assembly Programming]]

  asm-mode が標準添付.
  
* PHP
** php-mode
   - [[https://github.com/ejmr/php-mode][ejmr/php-mode]]

#+begin_src emacs-lisp
(use-package php-mode
  :commands php-mode
  :mode "\\.php$"
)
#+end_src

** mmm-mode
    php-mode と html-mode の同居.
    - [[http://bluestar.s32.xrea.com/text/php-mode.php][閑古鳥 -> 呟き -> emacs で PHP-mode と mmm-mode を使う]]

    Molokai テーマと相性が悪いので一旦消す.

#+begin_src emacs-lisp
; mmm-mode in php
;; (use-package mmm-mode)
;; (setq mmm-global-mode 'maybe)
;; (mmm-add-mode-ext-class nil "\\.php?\\'" 'html-php)
;; (mmm-add-classes
;;  '((html-php
;;     :submode php-mode
;;     :front "<\\?\\(php\\)?"
;;     :back "\\?>")))
;; (add-to-list 'auto-mode-alist '("\\.php?\\'" . xml-mode))
#+end_src


* DSL
** yaml-mode
 #+begin_src emacs-lisp
(use-package yaml-mode :commands yaml-mode)
 #+end_src

** rst-mode
   Major mode for editing Restructured Text

 #+begin_src emacs-lisp 
(use-package rst
  :commands rst-mode
  :mode (("\\.rst$" . rst-mode) ("\\.rest$" . rst-mode))
  :config
  ;; RST モードを見やすくする.
  (setq frame-background-mode 'dark)
  
  ;; 全部スペースでインデントしましょう
  ;; (add-hook 'rst-mode-hook '(lambda () (setq indent-tabs-mode nil)))
)
 #+end_src


** Plant UML Mode
   Major mode for editing PlantUML.
   - [[http://plantuml.sourceforge.net/emacs.html][PlantUML]]
   - [[http://futurismo.biz/archives/2305][Emacs から PlantUML を便利につかう方法 | Futurismo]]

   #+begin_src emacs-lisp
(use-package plantuml-mode
  :if linux-p
  :commands plantuml-mode
  :mode (("\\.puml$" . plantuml-mode)
	 ("\\.plantuml$" . plantuml-mode))
  :config
  (setq plantuml-jar-path "/usr/local/bin/plantuml.jar")
  )
 #+end_src

** ansible
   - https://github.com/k1LoW/emacs-ansible
   - [[http://k1low.hatenablog.com/entry/2014/05/27/231132][Ansible の Playbook を書くときに便利になるかもしれない ansible.el を書いてみた - Copy/Cut/Paste/Hatena]]

   submodule で ansible repo を clone していて,
   重かったのでいったん休止.

 #+begin_src emacs-lisp
(use-package ansible
  :disabled t
  :commands ansible)
 #+end_src


* wiki
** textile-mode
   Redmine wiki の記述用.
   - [[http://dev.nozav.org/textile-mode.html][Textile-mode · dev.nozav.org]]

   el-get じゃとれないかも
   - http://dev.nozav.org/scripts/textile-mode.el.
  
 #+begin_src emacs-lisp
(use-package textile-mode
  :mode ("\\.textile$" . textile-mode))
 #+end_src


** pukiwiki-mode
   pukiwiki-mode は minor-mode のみ使用する. 
   firefox や chrome の Edit 機能から, Emacs を起動する.

   - [[http://www.bookshelf.jp/pukiwiki/pukiwiki.php?%A5%A2%A5%A4%A5%C7%A5%A2%BD%B8%2Fpukiwiki-mode][アイデア集/pukiwiki-mode - Meadow memo]]
   - pukiwiki-mode.el  http://www.bookshelf.jp/elc/pukiwiki-mode.el
   - http.el http://tdiary.cvs.sourceforge.net/tdiary/contrib/util/tdiary-mode/
   - [[http://rmecab.jp/wiki/index.php?Wiki_pukiwiki-mode%A4%F2%C6%B3%C6%FE][Wiki_pukiwiki-mode を導入 - R と Linux と...]]

 #+begin_src emacs-lisp
(use-package pukiwiki-mode :commands (pukiwiki-mode pukiwiki-edit-mode))
 #+end_src


* HTML
** impatient-mode  
  インタラクティブな HTML の表示.
  - https://github.com/skeeto/impatient-mode

  M-x httpd-start をして, 以下にアクセス
  -  http://localhost:8080/imp/

#+begin_src emacs-lisp
(use-package impatient-mode)
#+end_src

  動かないなー. あとで再チャレンジする.

* Othres
** conkeror
   
 #+begin_src emacs-lisp
(use-package conkeror-minor-mode :commands conkeror-minor-mode)
 #+end_src
 


