#+TITLE: Utility
* Utility
  この elisp こそ, Emacs のすごさを示すものだ.

#+begin_src text
  Emacs は OS!
  Emacs は世界!
  Emacs は人生!
#+end_src

* elscreen
  screen の Emacs バージョン. マルチプレクサ.
  - https://github.com/emacs-jp/elscreen
  - https://github.com/knu/elscreen

  オリジナルはメンテナンスされていないのかな?
  - http://www.morishima.net/~naoto/elscreen-ja/
  - http://nishikawasasaki.hatenablog.com/entry/20110313/1300031344

  #+begin_src emacs-lisp
(use-package elscreen
  :config
  (elscreen-start)
  
  ;; (setq elscreen-prefix-key "\C-o") ;; こっちだとダメだった
  (elscreen-set-prefix-key "\C-o")
  
  ;; タブの幅
  ;; (setq elscreen-display-tab 10)
  
  ; タブの左端の×を非表示
  (setq elscreen-tab-display-kill-screen nil)

  ;; <>を非表示
  (setq elscreen-tab-display-control nil)
  
  ;; emacsclient で新しいタブを開く
  ;; (use-package elscreen-server nil t)
  )
#+end_src

** colors

   #+begin_src emacs-lisp
(custom-set-faces
 '(elscreen-tab-control-face ((t (:background "#1c1c1c" :foreground "#9e9e9e" :underline t))))
 '(elscreen-tab-current-screen-face ((t (:background "#444444" :foreground "#9e9e9e"))))
 '(elscreen-tab-other-screen-face ((t (:background "#262626" :foreground "#9e9e9e" :underline t)))))

;; それっぽい色をつける?? つけてくれないよ.
;; (use-package elscreen-color-theme)
#+end_src

** screen の順番を手軽に変更
   ここから
   - [[http://qiita.com/fujimisakari/items/d7f1b904de11dcb018c3][Emacs - Elscreen に機能追加する - Qiita]]
   - https://gist.github.com/tsu-nera/44763febe82874785bf7

#+begin_src emacs-lisp
(use-package elscreen-interchange
  :bind (("M-<tab>" . elscreen-swap-next))
  ;; (("C-M-<right>" . elscreen-swap-next)
  ;; ("C-M-<left>" . elscreen-swap-previous))
  )
#+end_src

** TODO org-link を elscreen で開く
   いつか.
** elscreen-persistent
   - [[http://www.robario.com/2014/12/08][elscreen を永続化する elscreen-persist を書いた #Emacs @robario]]
   - [[http://rubikitch.com/2014/12/11/elscreen-persist/][elscreen のウィンドウ構成が windows.el ばりに再起動時に復元できるゾ! ]]

   revive というパッケージに依存している??

#+begin_src emacs-lisp
(use-package elscreen-persist
  :config
  ;; どうもこれを有効にすると Emacs が立ち上がらなくなるな...
  ;; (elscreen-persist-mode 1)
  )
#+end_src

*** 以下で操作
   - elscreen-persist-store
   - elscreen-persist-restore

** elscreen-wl
   waanderlust 用. syohex さんのやつ.
   - [[http://d.hatena.ne.jp/syohex/20130129/1359471993][elscreen-wl を fork しました Life is very short]]

   w をおすと別タブで開くので, ちょい便利.
   
 #+begin_src emacs-lisp
;; (when windows-p
;;   (use-package elscreen-wl :defer t))
#+end_src

どこかで無限ループになっているな... 1 秒くらいここでかかっている.

#+begin_src text
Warning: Eager macro-expansion skipped due to cycle:
  … => (load "wl-e21.el") => (macroexpand-all …) => (macroexpand (eval-when-compile …)) => (load "wl-folder.el") => (macroexpand-all …) => (macroexpand (eval-when-compile …)) => (load "wl.el") => (load "wl-e21.el")
#+end_src

解決できないので封印.

** elscreen-dired
   dired で o をオスと別タブで開く.

   by wget https://raw.githubusercontent.com/knu/elscreen/master/elscreen-dired.el

#+begin_src emacs-lisp
(use-package elscreen-dired)
#+end_src

** Dired でカレントディレクトリを取得
  - [[http://d.hatena.ne.jp/syohex/20111026/1319606395][cde を改良 - Life is very short]]

#+begin_src emacs-lisp
(use-package cde)
#+end_src

* Web Browser: ブラウザ関連

#+begin_src emacs-lisp
(when linux-p
(setq browse-url-generic-program (executable-find "conkeror"))
(setq browse-url-browser-function 'browse-url-generic))

(when windows-p
; Windows 環境のデフォルト
 (setq browse-url-browser-function 'browse-url-default-windows-browser))

;; 今のポイントしている URL を開く
(global-set-key (kbd "C-c u") 'browse-url-at-point)
(define-key goto-map [?b] #'browse-url-at-point)
#+end_src

** 複数のブラウザを使い分け

** w3m
    eww が登場したのでもはや過去のもの. もう使わないだろう.

#+begin_src emacs-lisp
;; (use-package w3m-load
;;  :config
;;  (setq w3m-use-cookies t)
;;  (setq w3m-favicon-cache-expire-wait nil)
;;  (setq w3m-home-page "http://www.google.co.jp/")
;;  
;;  (when windows-p
;;    ;;(setq exec-path (append exec-path '("C://app//w3m-mingw32")))
;;    (setq exec-path (append exec-path '("C:/cygwin64/bin")))
;;    )
;;
;;  (setq w3m-user-agent  "Mozilla/5.0 (Linux; U; Android 2.3.3; zh-tw; 
;;        HTC_Pyramid Build/GRI40) AppleWebKit/533.1 
;;        (KHTML, like Gecko) Version/4.0 Mobile Safari/533.")
;;)
#+end_src

** webkit
   うごかない. . . .
   - [[https://github.com/linuxdeepin/deepin-emacs/tree/master/site-lisp/extensions/webkit][deepin-emacs/site-lisp/extensions/webkit at master · linuxdeepin/deepin-emacs]]

     - webkit/helm-webkit from github
     - epc from el-get
     - Pyqt5  yaourt -S python2-pyqt5 qt5-webkit
     - PythonXlib yaourt -S python2-xlib

#+begin_src emacs-lisp
;; (use-package webkit)
;; (use-package helm-webkit)
#+end_src

** eww
   24.4 から搭載の Web ブラウザ.
   - http://bzr.savannah.gnu.org/lh/emacs/trunk/annotate/head:/lisp/net/eww.el
   - [[http://www.gnu.org/software/emacs/manual/html_mono/eww.html#Advanced][Emacs Web Wowser]]

   - N (eww-next-url)
   - P (eww-previous-url) 
   - l (eww-back-url) 
   - r (eww-forward-url) 
   - H (eww-list-histories) 
   - & (eww-browse-with-external-browser)
   - b (eww-add-bookmark)
   - B (eww-list-bookmarks)
   - q (quit-window)

   見にくいときは, R eww-readable をすると, 
   余計なリンクやサイドバーが消えて見えやすくなる.
   
#+begin_src emacs-lisp
(use-package eww
  :commands (eww-disable-images)
  :bind (("C-q <C-return>" . eww)
	 ("C-x g g" . eww-search)
	 ("C-c p" . browse-url-with-eww))
  :config
  (define-key eww-mode-map "r" 'eww-reload)
  (define-key eww-mode-map "c 0" 'eww-copy-page-url)
  (define-key eww-mode-map "N" 'eww-next-url)
  (define-key eww-mode-map "P" 'eww-previous-url)
  (define-key eww-mode-map "p" 'scroll-down)
  (define-key eww-mode-map "n" 'scroll-up)
#+end_src

*** default の検索エンジンを変更
    google jp を設定する. default では, duckduckgo が設定されている.

    #+begin_src emacs-lisp
   (setq eww-search-prefix "http://www.google.co.jp/search?q=")
    #+end_src

    - https://duckduckgo.com/params

    こまかくパラメータ設定
    - kl=ja-jp 日本語
    - k1=-1    広告なし
    - kc=1     自動先読み
    - kf=-1    サイトアイコンなし
    - q =      検索文字

    => サイトアイコンなしは動かない.

    #+begin_src emacs-lisp
   ;; (setq eww-search-prefix "https://duckduckgo.com/html/?kl=jp-jp&k1=-1&kc=1&kf=-1&q=")
    #+end_src

*** 検索
    新しいバッファで検索結果を開く.

#+begin_src emacs-lisp
 (defun eww-search (term)
   (interactive "sSearch terms: ")
   (eww-browse-url (concat eww-search-prefix term)))
#+end_src

*** 現在の url を eww で開く
  - [[http://tototoshi.hatenablog.com/entry/20100630/1277897703][カーソル位置の URL をブラウザで開く - tototoshi の日記]]
  - [[http://stackoverflow.com/questions/9033050/how-to-setup-emacs-to-folow-links-in-two-ways-depend-on-ctrl-key][browser - How to setup Emacs to folow links in two ways depend on CTRL key - Stack Overflow]]
  - [[http://ergoemacs.org/emacs/elisp_thing-at-point.html][Emacs Lisp: Using thing-at-point]]
  - [[http://tech.actindi.net/3498443215][アクトインディ技術部隊報告書]]

  #+begin_src emacs-lisp
(defun browse-url-with-eww ()
  (interactive)
  (let ((url-region (bounds-of-thing-at-point 'url)))
    ;; url
    (if url-region
      (eww-browse-url (buffer-substring-no-properties (car url-region)
						      (cdr url-region))))
    ;; org-link
    (setq browse-url-browser-function 'eww-browse-url)
    (org-open-at-point)
    (setq browse-url-browser-function 'browse-url-generic)))
#+end_src

*** eww 複数起動はできない??
    バッファ名を rename すればいい.
    - http://ergoemacs.org/emacs/emacs_eww_web_browser.html

#+begin_src emacs-lisp
(defun eww-mode-hook--rename-buffer ()
  "Rename eww browser's buffer so sites open in new page."
  (rename-buffer "eww" t))
(add-hook 'eww-mode-hook 'eww-mode-hook--rename-buffer)
#+end_src

    - eww-list-buffers
      生成した eww を一覧で表示.

*** 外部ブラウザでリンクを開く (eww-browse-with-external-link)
    テキストブラウザは地味なので, ときには別のブラウザでも Web ページを閲覧したい.
    私は普段は conkeror を利用しているので, これで開きたい.

    以下の関数で今見ているページを外部ブラウザで開くことができる.
    &にキーバインドされている.

    #+begin_src text
    eww-browse-with-external-link
    #+end_src

    以下の設定で, ブラウザを conkeror に指定.
    - http://www.emacswiki.org/emacs/Conkeror

#+begin_src emacs-lisp
(setq shr-external-browser 'browse-url-generic)
#+end_src

*** conkerror のような番号づけ
    eww-lnum を入れると, conkeror のようにリンク先を選択できる.

    - https://github.com/m00natic/eww-lnum
    - [[http://rubikitch.com/2014/11/12/eww-lnum/][emacs eww-lnum.el : 組み込みブラウザ eww で Hit-a-Hint しようぜ ]]
    つまり, f を押すことで, リンク先に番号が振られるので,
    番号を選択することでリンク先を選択できる.

    -> ace-link でおきかえのため, 一旦 disable.

#+begin_src emacs-lisp
(use-package eww-lnum
  :disabled t
  :commands (eww-lnum-follow eww-lnum-universal)
  :init
  (define-key eww-mode-map "f" 'eww-lnum-follow)
  (define-key eww-mode-map "F" 'eww-lnum-universal)
  :config
  (defun eww-lnum-read-interactive--not-truncate-lines (&rest them)
    (let ((truncate-lines nil))
      (apply them)))
  (advice-add 'eww-lnum-read-interactive :around
	      'eww-lnum-read-interactive--not-truncate-lines))
#+end_src

*** 背景色の設定
    - [[http://rubikitch.com/2014/11/19/eww-nocolor/][Emacs24.4 組み込みブラウザ eww で目の疲れを 1/10 にする方法 | るびきち「日刊 Emacs 」]]

#+begin_src emacs-lisp
(defvar eww-disable-colorize t)
(defun shr-colorize-region--disable (orig start end fg &optional bg &rest _)
  (unless eww-disable-colorize
    (funcall orig start end fg)))
(advice-add 'shr-colorize-region :around 'shr-colorize-region--disable)
(advice-add 'eww-colorize-region :around 'shr-colorize-region--disable)
(defun eww-disable-color ()
  "eww で文字色を反映させない"
  (interactive)
  (setq-local eww-disable-colorize t)
  (eww-reload))
(defun eww-enable-color ()
  "eww で文字色を反映させる"
  (interactive)
  (setq-local eww-disable-colorize nil)
  (eww-reload))
#+end_src

*** helm-eww-history
    - [[http://rubikitch.com/2014/11/26/helm-eww/][helm-eww.el – Emacs 組み込み Web ブラウザ eww で URL の履歴を helm する ]]

#+begin_src emacs-lisp
(use-package helm-eww-history)
#+end_src

*** helm-eww-bookmarks

#+begin_src emacs-lisp
(use-package helm-eww-bookmark
  :disabled t
  :config
   (define-key eww-mode-map "B" 'helm-eww-bookmark))
#+end_src

*** proxy 越え
   - [[http://rubikitch.com/2014/11/17/eww-proxy/][Emacs で proxy を使う設定 – この 1 行で eww も package も広告避けもバッチリ! | るびきち「日刊 Emacs 」]]

*** 画像表示
   -  [[http://rubikitch.com/2014/11/25/eww-image/][Emacs24.4/Emacs25 の eww で画像を非表示にする方法! よりテキストブラウザらしく]]

#+begin_src emacs-lisp
(defun eww-disable-images ()
  "eww で画像表示させない"
  (interactive)
  (setq-local shr-put-image-function 'shr-put-image-alt)
  (eww-reload))
(defun eww-enable-images ()
  "eww で画像表示させる"
  (interactive)
  (setq-local shr-put-image-function 'shr-put-image)
  (eww-reload))
(defun shr-put-image-alt (spec alt &optional flags)
  (insert alt))
;; はじめから非表示
(defun eww-mode-hook--disable-image ()
  (setq-local shr-put-image-function 'shr-put-image-alt))
(add-hook 'eww-mode-hook 'eww-mode-hook--disable-image)
#+end_src

*** 検索
    - http://rubikitch.com/2014/11/20/eww-weblio/
    
#+begin_src emacs-lisp
;; (use-package eww-weblio)
#+end_src

*** get-link
    eww-copy-page-url (w) で現在の URL をクリップボードにコピー.

    #+begin_src emacs-lisp
(defvar eww-org-link-buffer "")
(defun eww-copy-page-org-link ()
  (interactive)
  (setq eww-org-link-buffer
	(format "[[%s][%s]]" (eww-current-url) (eww-current-title))))
(defun eww-yank-page-org-link ()
  (interactive)
  (insert eww-org-link-buffer))
(define-key eww-mode-map (kbd "@") 'eww-copy-page-org-link)
(define-key org-mode-map (kbd "C-x @ @") 'eww-yank-page-org-link)
#+end_src

*** eww-hatebu
    - 
    - [[http://d.hatena.ne.jp/syohex/20150116/1421424603][eww ではてなブックマーク数を表示する拡張を書いた - Life is very short]]    

#+begin_src emacs-lisp
(use-package eww-hatebu
  :config
  (eww-hatebu-setup)
  (custom-set-faces
   '(eww-hatebu-bookmarks
     ((t (:foreground "#A6E22E"))))))
#+end_src

*** end of config

#+begin_src emacs-lisp
   )
#+end_src

** edit-server
   Google Chrome のフォームを emacs で編集. Edit with Emacs.
   - https://github.com/stsquad/emacs_chrome/blob/master/servers/edit-server.el

 #+begin_src emacs-lisp
(use-package edit-server
  :defer t
  :config
  (setq edit-server-new-frame nil)
  ;; 手動で起動にする.
  ;; (edit-server-start)
  )
 #+end_src

* ディレクトリ操作
** dired

#+begin_src emacs-lisp
;; ディレクトリから表示
(setq ls-lisp-dirs-first t)
#+end_src

*** dired から open
#+begin_src emacs-lisp
(when linux-p
(defun dired-open-file ()
  "In dired, open the file named on this line."
  (interactive)
  (let* ((file (dired-get-filename nil t)))
    (message "Opening %s..." file)
    (call-process "xdg-open" nil 0 nil file)
    (message "Opening %s done" file)))

(add-hook
   'dired-mode-hook
   (lambda ()
     (define-key dired-mode-map [f6] 'dired-open-file)))
)
#+end_src

*** dired から term へ
    - [[http://oremacs.com/2015/01/10/dired-ansi-term/][dired and ansi-term: BFF · (or emacs]]

    eshell-cmd がないと怒られる.

#+begin_src emacs-lisp
;; (define-key dired-mode-map (kbd "'")
;;   (lambda ()
;;     (interactive)
;;     (eshell-cmd
;;      (format "cd %s"
;;              (expand-file-name
;;               default-directory)))))
#+end_src

*** 移動のたびに新規バッファをつくらない
    移動のたびにバッファをつくらないためには, i や a でバッファを開く.
    - [[http://stackoverflow.com/questions/1839313/how-do-i-stop-emacs-dired-mode-from-opening-so-many-buffers][file management - How do I stop emacs dired mode from opening so
      many buffers? - Stack Overflow]]

    or 

#+begin_src emacs-lisp
(put 'dired-find-alternate-file 'disabled nil)
#+end_src

  - [[http://macemacsjp.sourceforge.jp/index.php?EmacsDired][EmacsDired - MacEmacs]]

** joseph-single-dired
   バッファを複数作成しない.
   - https://github.com/jixiuf/joseph-single-dired

#+begin_src emacs-lisp
(use-package joseph-single-dired)
#+end_src

** Tramp
   リモートサーバに Emacs から乗り込む.

   こんな感じで乗り込む.
   - C-x C-f /ssh:username@hostname#portno:/path/to/your/directory

   Tramp で save 時に毎回パスワードが聞かれるので, おまじない.
   - [[http://stackoverflow.com/questions/840279/passwords-in-emacs-tramp-mode-editing][ssh - Passwords in Emacs tramp mode editing - Stack Overflow]]

#+begin_src emacs-lisp
(setq password-cache-expiry nil)
#+end_src

** dired-x
   dired の拡張.

#+begin_src emacs-lisp
(use-package dired-x)
#+end_src
** direx
   popup dired
   - https://github.com/m2ym/direx-el
   - http://cx4a.blogspot.jp/2011/12/popwineldirexel.html

   使っていないのと, open-junk-file とキーがかぶったので封印.
#+begin_src emacs-lisp
;; (use-package direx)
#+end_src


* パスワード管理
** netrc
   build-in のパスワード管理.
   パスワード自体は ~/.netrc に書き込む. 

#+begin_src emacs-lisp
(use-package netrc :defer t)
#+end_src


* Shell
  いろいろシェルはあるのだけれども,
  eshell ひとつに絞ってしまおう.

** eshell
   - [[http://www.bookshelf.jp/pukiwiki/pukiwiki.php?Eshell%A4%F2%BB%C8%A4%A4%A4%B3%A4%CA%A4%B9][Eshell を使いこなす - Meadow memo]]
   - [[http://qiita.com/fnobi/items/8906c8e7759751d32b6b][terminal を棄てて Emacs と心中するための設定 - Qiita]]

   TODO あとで試す
   - [[http://d.hatena.ne.jp/syohex/20130127/1359269462][簡易 eshell-pop, cde, cdp - Life is very short]]

   #+begin_src emacs-lisp
;; shell のキーバインド
(global-set-key (kbd "C-c t") 'eshell)

;; 確認なしでヒストリ保存
(setq eshell-ask-to-save-history (quote always))
 ;; 補完時にサイクルする
(setq eshell-cmpl-cycle-completions nil)
;; 補完時に大文字小文字を区別しない
(setq eshell-cmpl-ignore-case t)

(setq eshell-save-history-on-exit t)
(setq eshell-cmpl-dir-ignore "\\`\\(\\.\\.?\\|CVS\\|\\.svn\\|\\.git\\)/\\'")

;;補完候補がこの数値以下だとサイクルせずに候補表示
;; (setq eshell-cmpl-cycle-cutoff-length 5)

;; 履歴で重複を無視する
(setq eshell-hist-ignoredups t)

;; これで正規表現がつかえるようになる??
(setq eshell-prompt-regexp "^[^#$]*[$#] ")

;; windows 環境だと, shift-jis にしよう
(when windows-p
  (add-hook
   'eshell-mode-hook
   '(lambda ()
      (set-buffer-process-coding-system 'sjis 'sjis))))

(setq eshell-prompt-function
      (lambda ()
        (concat "[tsu-nera"
                (eshell/pwd)
                (if (= (user-uid) 0) "]\n# " "]\n$ ")
                )))

;; eshell の alias 設定
;; http://www.emacswiki.org/emacs/EshellAlias
(setq eshell-command-aliases-list
      (append
       (list
        (list "ll" "ls -ltr")
        (list "la" "ls -a")
        (list "o" "xdg-open")
	(list "emacs" "find-file $1")
	(list "m" "find-file $1")
	(list "mc" "find-file $1")	
        (list "less" "eshell/less")
        (list "l" "eshell/less")		
        (list "forced_git_local_destroy" "git fetch origin;git reset --hard origin/master")
       )))
;;       eshell-command-aliases-list))
#+end_src

*** eshell-utils
    関数は別ファイルにわけてバイトコンパイルする.

#+begin_src emacs-lisp
(use-package eshell-utils
  :bind (;; バッファと eshell を toggle
         ("<C-M-return>" . eshell/toggle-buffer)
         ;; 別シェルを生成
         ("C-c C-x t" . eshell/make-new-eshell))
  :init
  (define-key dired-mode-map (kbd "`") 'eshell/toggle-buffer)
;;  (add-hook 'eshell-mode-hook
;;	    #'(lambda ()
;;		(define-key eshell-mode-map (kbd "C-l") 'eshell/clear)))
  )
#+end_src

*** eshell with helm
    - https://github.com/emacs-helm/helm/blob/master/helm-eshell.el
    - https://github.com/emacs-helm/helm/wiki#helmeshellcompletion
    - [[http://nishikawasasaki.hatenablog.com/entry/2012/09/12/233116][helm で eshell が便利 - あじーん-0.0.2-SNAPSHOT]]

    つかいかた
    - helm-esh-pcomplete helm で補完
      ほんとは tab に bind したいのだが, できない.
      http://www.gnu.org/software/emacs/manual/html_node/eshell/Completion.html
    - helm-eshell-history 履歴から入力

    #+begin_src emacs-lisp
(use-package helm-eshell
  :init
  (add-hook 'eshell-mode-hook
	    #'(lambda ()
		(define-key eshell-mode-map [remap eshell-pcomplete] 'helm-esh-pcomplete)))
  
  (add-hook 'eshell-mode-hook
	    #'(lambda ()
                (define-key eshell-mode-map (kbd "M-p") 'helm-eshell-history))))

;; なぜか helm がじゃまをするな.
;; (add-to-list 'helm-completing-read-handlers-alist '(make-eshell . nil))
#+end_src

** exec-path-from-shell
   環境変数 PATH を引き継ぐ.
   - [[https://github.com/purcell/exec-path-from-shell][purcell/exec-path-from-shell]]
   - http://sakito.jp/emacs/emacsshell.html#emacs

#+begin_src emacs-lisp
(use-package exec-path-from-shell
  :config
  (when (memq window-system '(mac ns))
    (exec-path-from-shell-initialize)))
;;   (exec-path-from-shell-initialize))
#+end_src

* Chat
** twittering-mode
  Emacs Twitter Client
  - [[http://www.emacswiki.org/emacs/TwitteringMode-ja][EmacsWiki: TwitteringMode-ja]]

#+begin_src emacs-lisp
(use-package twittering-mode
  :bind ("C-c C-x w" . twittering-update-status-from-pop-up-buffer)
  :config
  (setq twittering-use-master-password t)
  ;; パスワード暗号ファイル保存先変更 (デフォはホームディレクトリ)
  (setq twittering-private-info-file "~/.emacs.d/twittering-mode.gpg")
  )
#+end_src

*** popwin に閉じ込める
   このアイデアは good idea.
   - [[http://d.hatena.ne.jp/lurdan/20130225/1361806605][twittering-mode を popwin に閉じこめる - *scratch*]]

** bitlbee
  yaourt bitlbee でいれた.
  - [[https://wiki.archlinux.org/index.php/bitlbee][Bitlbee - ArchWiki]]
  - [[http://www.emacswiki.org/emacs/BitlBee][EmacsWiki: Bitl Bee]]
  - [[http://emacs-fu.blogspot.jp/2012/03/social-networking-with-bitlbee-and-erc.html][emacs-fu: social networking with bitlbee and erc]]

まだ動かした実績はなし. . . とりあえず入れておくか.

#+begin_src emacs-lisp
;; (use-package bitlbee)
;; (defun i-wanna-be-social ()
;;   "Connect to IM networks using bitlbee."
;;   (interactive)
;;   (erc :server "localhost" :port 6667 :nick "user"))
#+end_src

** ERC
   Emacs のチャットツール.
  
   - [[http://www.emacswiki.org/ERC][EmacsWiki: ERC]]
   - [[http://en.wikipedia.org/wiki/ERC_(software)][ERC (software) - Wikipedia, the free encyclopedia]]
   - [[http://emacs-fu.blogspot.jp/2009/06/erc-emacs-irc-client.html][emacs-fu: ERC: the emacs IRC client]]
   - [[http://sleepboy-zzz.blogspot.jp/2013/07/emacs-ercirc.html][memo: Emacs ERC で IRC を試してみた]]

#+begin_src emacs-lisp
;; (use-package erc
;;  :commands erc
;;  :config

;; 調子がわるいので, use-package をやめてみる.
(when windows-p
(require 'erc)

  ;; ログイン情報
  ;; (setq erc-server "localhost")
  ;; (setq erc-port "6667")
  ;; (setq erc-nick "tsu-nera")
  ;; (setq erc-password "")

  (defmacro de-erc-connect (command server port nick)
    "Create interactive command `command', for connecting to an IRC server. The
command uses interactive mode if passed an argument."
    (fset command
	  `(lambda (arg)
	     (interactive "p")
	     (if (not (= 1 arg))
		 (call-interactively 'erc)
	       (erc :server ,server :port ,port :nick ,nick)))))
  
  ;; (de-erc-connect erc-opn "localhost" 6667 "tsu-nera")
#+end_src

*** ログアウト
    - /PART Channel をさる
    - /QUIT msg Server をさる
    - [[http://www.emacswiki.org/emacs/ErcStartupFiles][EmacsWiki: Erc Startup Files]]

#+begin_src emacs-lisp
;; Kill buffers for channels after /part
(setq erc-kill-buffer-on-part t)
#+end_src

*** ニックネームハイライト
**** erc-highlight-nicknames
    - [[http://www.emacswiki.org/ErcHighlightNicknames][EmacsWiki: Erc Highlight Nicknames]]

 #+begin_src emacs-lisp
;; (and
;;   (use-package erc-highlight-nicknames)
;;   (add-to-list 'erc-modules 'highlight-nicknames)
;;   (erc-update-modules))
 #+end_src

**** erc-hl-nicks
     erc-highlight-nicknames の改良版か?
   - https://github.com/leathekd/erc-hl-nicks

 #+begin_src emacs-lisp
(use-package erc-hl-nicks :defer t)
 #+end_src

*** 通知
**** ERC notification
     登録した単語をみつけたら反応する.
     - [[https://julien.danjou.info/blog/2012/erc-notifications][ERC notifications Julien Danjou]]

#+begin_src emacs-lisp
(add-to-list 'erc-modules 'notifications)
(erc-update-modules)
(setq erc-pals '("tsune" "tsu-nera")
      erc-notify-list erc-pals)
#+end_src
      
**** erc-nick-notify
     呼ばれたら反応する.
     - [[http://www.emacswiki.org/emacs/ErcNickNotify][EmacsWiki: Erc Nick Notify]]
     
     notify-send しか対応していないみたい. Linux 用..
    
     #+begin_src emacs-lisp
(use-package erc-nick-notify
  :commands erc-nick-notify-mode
  :config
  (erc-nick-notify-mode t))
#+end_src
 
**** erc-input-lien-position
 #+begin_src emacs-lisp
(setq erc-input-line-position -2)
 #+end_src

**** growl
     Growl できるっぽい. Growl for windows で通知できるか??
     - [[http://www.emacswiki.org/emacs/ErcGrowl][EmacsWiki: Erc Growl]]
     - https://github.com/samaaron/samaaron-pack/blob/master/config/erc-growl.el
     - https://gist.github.com/danielsz/ac19353e718dde3dea72
     - [[http://qiita.com/rohinomiya/items/5e485d6700eac256af9f][Windows で Growl 通知を行う - Qiita]]

    Growl を利用すると, Alt+x, Alt+Shift+x が利用できなくなるという
    致命的な問題がある.

    %USERPROFILE%\Local Settings\Application Data\Growl\2.0.0.0\user.config

    で Alt+X とかいてあるところをべつのものに修正すればいい.
    - [[http://stackoverflow.com/questions/6495050/how-can-i-use-alt-as-meta-key-in-windows-for-emacs-23-especially-m-x][How can I use Alt as meta key in Windows for Emacs 23, especially M-x? - Stack Overflow]]
    - https://groups.google.com/forum/#!topic/growl-for-windows/Yu3bo3EZ9SA

    To Do Chi Ku という通知用のインタファースもあるが動かなかった
    - [[http://www.emacswiki.org/emacs/ToDoChiKu][EmacsWiki: To Do Chi Ku]]
    - [[http://justinsboringpage.blogspot.jp/2009/09/making-emacs-growl.html][justinhj's coding blog: Making emacs growl]]

#+begin_src emacs-lisp
(when windows-p
  (use-package my-growl-for-windows)
  )
#+end_src

#+RESULTS:
: Could not load package my-growl-fow-windows

*** Encoding
    #+begin_src emacs-lisp
   ;; UTF-8
   ;; (setq  erc-server-coding-system '(utf-8 . utf-8))

   ;; Shift-JIS
   ;; (setq erc-server-coding-system に (iso-2022-jp . iso-2022-jp))
    #+end_src

*** width を可変にする
    デフォルトは 78 で折り返し.
    - [[http://www.emacswiki.org/emacs/ErcFilling][EmacsWiki: Erc Filling]]

#+begin_src emacs-lisp
(add-hook 'window-configuration-change-hook 
	  '(lambda ()
	     (setq erc-fill-column (- (window-width) 2))))
#+end_src
*** End of ERC Config
#+begin_src emacs-lisp
)
#+end_src

* Hown
  Function : Evernote を越えるメモ管理ツール
  - http://www.gfd-dennou.org/member/uwabami/cc-env/emacs/howm_config.html
  - http://d.hatena.ne.jp/TakashiHattori/20120627/1340768058

  使いこなせてないので封印.いつか, 使いこなしたい.

#+begin_src emacs-lisp
;; *.org を開いたら howm-mode も起動する
;;(add-hook 'org-mode-hook 'howm-mode)

;; howm のメモを置くディレクトリ (任意)
;; (setq howm-directory "~/gtd/howm") ;; メニュー表示しない
;; (setq howm-menu-top nil)
;; メニューの言語設定
;; (setq howm-menu-lang 'ja)
;; howm ファイル名を設定する. org-mode を起動するため拡張子は .org にする.
;; (setq howm-file-name-format "%Y%m%d-%H%M%S.org")
;; (setq howm-view-title-header "*") ;; ← howm のロードより前に書くこと

;; キーバインドは C-a C-a にする
;; (global-unset-key (kbd "C-x C-a"))
;; (setq howm-prefix (kbd "C-x C-a"))

;;(autoload 'howm "howm" " Hitori Otegaru Wiki Modoki" nil)
;; (use-package howm)
;; (add-hook 'howm-mode-hook 'helm-howm)
;; (use-package helm-howm)
#+end_src

* pdf-tools
  PDF Viewer.
  - https://github.com/politza/pdf-tools
  - http://www.dailymotion.com/video/x2bc1is_pdf-tools-tourdeforce_tech?forcedQuality%3Dhd720
  - http://sheephead.homelinux.org/2014/03/17/7076/

  github のやつだと, コンパイルエラーするので, fork して無理やり通した.
  -> patch とりこまれた

  ArchLinux では, GhostScript を入れる.

#+begin_src sh
sudo pacman -S ghostscript
#+end_src

#+begin_src emacs-lisp
(use-package pdf-tools
  :if linux-p
  :init
  (setq pdf-info-epdfinfo-program
	(concat (el-get-package-directory "pdf-tools") "src/epdfinfo"))
  (add-hook 'pdf-view-mode
 	    (lambda ()
	      (pdf-isearch-minor-mode)))
  :mode (("\\.pdf$" . pdf-view-mode)))
;;  :config
  
  
  

;; (defconst 
;; '(pdf-history-minor-mode
;; 
;; pdf-links-minor-mode
;; pdf-misc-minor-mode
;; pdf-outline-minor-mode
;; pdf-misc-size-indication-minor-mode
;; pdf-misc-menu-bar-minor-mode
;; pdf-annot-minor-mode
;; pdf-sync-minor-mode
;; pdf-misc-context-menu-minor-mode
;; pdf-cache-prefetch-minor-mode))	      
	      ;; (use-package pdf-isearch)
	      ;; (use-package pdf-annot)
	      ;; (use-package pdf-history) 
	      ;; (use-package pdf-info)
	      ;; (use-package pdf-links) 
	      ;; (use-package pdf-misc) 
	      ;; (use-package pdf-occur) 
	      ;; (use-package pdf-outline) 
	      ;; (use-package pdf-sync) 
	      ;; (use-package tablist-filter)
	      ;; (use-package tablist))))
#+end_src

  どうも, doc-view-mode がめちゃくちゃ遅い!linum-mode が有効なことが原因.
  以下のページを参考に, major-mode が 
  - doc-view-mode
  - pdf-view-mode
  のときは, linum-mode は disable に.
  - [[http://stackoverflow.com/questions/16132234/how-can-i-speed-up-emacs-docview-mode][How can I speed up Emacs DocView mode? - Stack Overflow]]

** WIndows 環境
   頑張ってる. まだうごかない.

   - libglib
   - libglib-dev
   - libpopper
   - libpoppwer-glib8

* calfw
  Emacs 用カレンダー.
  -> org-mode に移動.

* Google
** google-translate
   Google 翻訳.
   - [[http://qiita.com/catatsuy/items/ae9875706769d4f02317][卒論を英語で書けと言われしまったあなたにおすすめの Emacs の設定 - Qiita]]
   - [[http://rubikitch.com/2014/12/07/google-translate/][emacs google-translate.el : Google 翻訳で言語自動判別しつつ英訳・和訳する!]]
   
#+begin_src emacs-lisp
(use-package google-translate
  :bind (("C-x t" . google-translate-enja-or-jaen)
	 ("C-x T" . google-translate-query-translate))
  :init
  ;; ;; 翻訳のデフォルト値を設定 (ja -> en) (無効化は C-u する)
  ;; -> patch で自動判別
  ;; (custom-set-variables
  ;;  '(google-translate-default-source-language "ja")
  ;;  '(google-translate-default-target-language "en"))
  :config
  (use-package my-patch-google-translate)
  )
#+end_src

** google-this
   Google 検索. これは便利だぁ.
   - [[https://github.com/Bruce-Connor/emacs-google-this][Bruce-Connor/emacs-google-this]]

   代表的な使用方法.
   - C-c / g (RET) でその場のキーワード検索.
   - C-c / w でその場のワードを検索
   - C-c / l でその行を検索
   - C-c / c Google 翻訳

#+begin_src emacs-lisp
(use-package google-this
  :config
  (google-this-mode 1))
#+end_src

* Dictionary
** search-web
    無料でオンラインの英辞郎 on the WEB をサクッと利用する.

    - [[https://github.com/tomoya/search-web.el/tree/master][tomoya/search-web.el]]
    - [[http://qiita.com/akisute3@github/items/8deb54b75b48e8b04cb0][Emacs 使用中に素早く検索する - Qiita]]
    - [[http://d.hatena.ne.jp/tomoya/20090703/1246610432][Emacs ですぐに単語の検索をしたい欲望を叶える Elisp. - 日々, とん
      は語る. ]]

    とくに, キーバインドはつけてない.

#+begin_src emacs-lisp
(use-package search-web :defer t)
;; 英辞郎 ... なんかうごかないな.
;; (define-key global-map (kbd "C-x g e") (lambda () (interactive) (search-web-at-point "eow")))
;; (define-key global-map (kbd "C-x g C-e") (lambda () (interactive) (search-web-region "eow")))
#+end_src

** codic
   エンジニアのためのネーミング辞書.

   M-x codic xxx

#+begin_src emacs-lisp
(use-package codic :defer t)
#+end_src

* Pomodoro
  ポモドーロ関係のツール.
  - [[http://pomodorotechnique.com/][HOME - The Pomodoro Technique ® The Pomodoro Technique ®]]

** 一覧
  - https://github.com/konr/tomatinho
  - http://ivan.kanis.fr/pomodoro.el
  - https://github.com/lolownia/org-pomodoro
  - https://github.com/baudtack/pomodoro.el

** tomatinho
ちょっとかわったポモドーロツール.

- https://github.com/konr/tomatinho

使わないので一旦封印.

#+begin_src emacs-lisp
;; (use-package tomatinho)
;; (global-set-key (kbd "<f12>") 'tomatinho)
;; (define-key tomatinho-map (kbd "N") 'tomatinho-interactive-new-pomodoro)
;; (define-key tomatinho-map (kbd "P") 'tomatinho-interactive-deliberate-pause)
;; (define-key tomatinho-map (kbd "T") 'tomatinho-interactive-toggle-display)
#+end_src

** pomodoro.el
   なんか, pomodoro.el が 同じ名前で 3 つもある気がする.
   とりあえず, el-get のレシピがあったものを利用.

   - [[https://github.com/syohex/emacs-utils][syohex/emacs-utils]]
   - [[http://d.hatena.ne.jp/syohex/20121215/1355579575][Emacs でポモドーロテクニック - Life is very short]]

   使わないので一旦封印.

#+begin_src emacs-lisp
;; (use-package pomodoro)

;; (when linux-p
;; ;; hook 関数関連
;; (use-package notifications)
;; (defun* my/pomodoro-notification (&key (title "Pomodoro")
;;                                        body
;;                                        (urgency 'normal))
;;   (notifications-notify :title title :body body :urgency urgency))

;; ;; 作業終了後の hook
;; (add-hook 'pomodoro:finish-work-hook
;;           (lambda ()
;;             (my/pomodoro-notification :body "Work is Finish")
;; 	    (rest)
;; 	    (shell-command "mplayer /usr/share/sounds/freedesktop/stereo/service-login.oga >/dev/null 2>&1")
;; 	    ))

;; ;; 休憩終了後の hook
;; (add-hook 'pomodoro:finish-rest-hook
;;           (lambda ()
;;             (my/pomodoro-notification :body "Break time is finished")
;; 	    (shell-command "mplayer /usr/share/sounds/freedesktop/stereo/service-login.oga >/dev/null 2>&1")
;; 	    ))
;; )
#+end_src

* psession
  セッション保存. elscreen に対応してくれないかな. . .
  - [[https://github.com/thierryvolpiatto/psession][thierryvolpiatto/psession]]
  - [[http://rubikitch.com/2014/08/21/psession/][Emacs のデータ・バッファ・ウィンドウ構成を永続化し, 再起動時に復元する方法 るびきち× Emacs]]

  -> elscreen-persist に以降したので一旦封印.

#+begin_src emacs-lisp
(use-package psession
  :disabled t
  :config
  (autoload 'psession-mode "persistent-sessions.el")
  (psession-mode 1)
  )
#+end_src
