* ターミナル
  主にターミナル操作に関する機能.
  - ファイラ
  - シェル
  - ウィンドウマネージャー

* Shell
  いろいろシェルはあるのだけれども,eshell ひとつに絞ってしまおう.

** eshell
   - [[http://qiita.com/fnobi/items/8906c8e7759751d32b6b][terminal を棄てて Emacs と心中するための設定 - Qiita]]

 #+begin_src emacs-lisp
(use-package eshell
  :init
;;  (global-set-key (kbd "C-c t") 'eshell)
  :config
  
  ;; 確認なしでヒストリ保存
  (setq eshell-ask-to-save-history (quote always))
  ;; 補完時にサイクルする
  (setq eshell-cmpl-cycle-completions nil)
  ;; 補完時に大文字小文字を区別しない
  (setq eshell-cmpl-ignore-case t)

  (setq eshell-save-history-on-exit t)
  (setq eshell-cmpl-dir-ignore "\\`\\(\\.\\.?\\|CVS\\|\\.svn\\|\\.git\\)/\\'")

  ;;補完候補がこの数値以下だとサイクルせずに候補表示
  ;; (setq eshell-cmpl-cycle-cutoff-length 5)

  ;; 履歴で重複を無視する
  (setq eshell-hist-ignoredups t)

  ;; これで正規表現がつかえるようになる??
  (setq eshell-prompt-regexp "^[^#$]*[$#] ")

  ;; スクロールがカクカクなるのを抑止する.
  ;; http://stackoverflow.com/questions/12667043/emacs-smooth-scrolling-scroll-margin-and-eshell
  ;; (setq scroll-margin 0)

  ;; zsh の環境変数を取り込む
  ;; http://d.hatena.ne.jp/zonu_exe/20120509/1336583187
  (let ((zshpath (shell-command-to-string "/usr/bin/zsh -c 'printenv PATH'")))
    (let ((pathlst (split-string zshpath ":")))
      (setq exec-path pathlst))
    (setq eshell-path-env zshpath)
    (setenv "PATH" zshpath))

  ;; windows 環境だと, shift-jis にしよう
  (when windows-p
    (add-hook
     'eshell-mode-hook
     '(lambda ()
        (set-buffer-process-coding-system 'sjis 'sjis))))
#+end_src

*** format
    prompt のフォーマット

#+begin_src emacs-lisp
;; (setq eshell-prompt-function
;;       (lambda ()
;;         (concat "[tsu-nera:"
;;                 (eshell/pwd)
;;                 ;;                (if (= (user-uid) 0) "]\n# " "]\n$ "))))
;;                 (if (= (user-uid) 0) "]\n# " "]\n$ "))))
#+end_src

*** color
    - [[http://www.emacswiki.org/emacs/EshellColor][EmacsWiki: Eshell Color]]

#+begin_src emacs-lisp
;; (eval-after-load "ansi-color"
;;   '(progn
;;      (defun eshell-handle-ansi-color ()
;;        (ansi-color-apply-on-region eshell-last-output-start
;;                                    eshell-last-output-end))
;;      (add-to-list 'eshell-output-filter-functions 'eshell-handle-ansi-color)))
#+end_src

**** eshell-prompt-extras
     eshell のポップアップ色付け.
     - https://github.com/hiddenlotus/eshell-prompt-extras

#+begin_src emacs-lisp
(use-package eshell-prompt-extras
  :config
  ;; git は無効. なぜか遅くなるので.  
  (defun epe-git-p () nil)
  (setq eshell-highlight-prompt nil
        ;; eshell-prompt-function 'epe-theme-lambda))
           eshell-prompt-function 'epe-theme-dakrone))
        ;; eshell-prompt-function 'epe-theme-geoffgarside))
#+end_src

*** eshell alias
    eshell の alias 設定
    - http://www.emacswiki.org/emacs/EshellAlias

    eshell 上では eshell/hoge というコマンドは hoge に置き換えられる.

#+begin_src emacs-lisp
  (setq eshell-command-aliases-list
        (append
         (list
          (list "ll" "ls -ltr")
          (list "la" "ls -a")
          (list "o" "xdg-open")
          (list "emacs" "find-file $1")
          (list "m" "find-file $1")
          (list "mc" "find-file $1")	
          (list "l" "eshell/less $1")
          (list "d" "dired .")		          
          (list "forced_git_local_destroy" "git fetch origin;git reset --hard origin/master")
          (list "ff" "find-file $1")
          (list "FF" "find-file-other-window $1")
          (list "v" "view-file $1")
          (list "V" "view-file-other-window $1")
          )))
#+end_src

*** eshell-utils
    関数は別ファイルにわけてバイトコンパイルする.

#+begin_src emacs-lisp
(use-package eshell-utils
  :bind* (("C-u C-c t" . eshell/make-new-eshell))) ;; 別シェルを生成
#+end_src
*** eshell with helm
    - https://github.com/emacs-helm/helm/blob/master/helm-eshell.el
    - https://github.com/emacs-helm/helm/wiki#helmeshellcompletion
    - [[http://nishikawasasaki.hatenablog.com/entry/2012/09/12/233116][helm で eshell が便利 - あじーん-0.0.2-SNAPSHOT]]

    つかいかた
    - helm-esh-pcomplete helm で補完
      ほんとは tab に bind したいのだが, できない.
      http://www.gnu.org/software/emacs/manual/html_node/eshell/Completion.html
    - helm-eshell-history 履歴から入力

    #+begin_src emacs-lisp
(use-package helm-eshell
  :init
  ;; (add-hook 'eshell-mode-hook
  ;;         #'(lambda ()
  ;;             (define-key eshell-mode-map [remap pcomplete] 'helm-esh-pcomplete)))  
 (add-hook 'eshell-mode-hook
          #'(lambda ()
              (define-key eshell-mode-map [remap eshell-pcomplete] 'helm-esh-pcomplete)))
  (add-hook 'eshell-mode-hook
	    #'(lambda ()
                (define-key eshell-mode-map (kbd "M-p") 'helm-eshell-history))))

;; なぜか helm がじゃまをするな.
;; (add-to-list 'helm-completing-read-handlers-alist '(make-eshell . nil))
#+end_src

*** multi-eshell
    - https://github.com/emacsmirror/multi-eshell/blob/master/multi-eshell.el
    
#+begin_src emacs-lisp
(use-package multi-eshell
  :init
  (global-set-key (kbd "C-c t t") 'multi-eshell)
  :config
  (setq multi-eshell-shell-function '(eshell))
  (setq multi-eshell-name "*eshell*"))
#+end_src

**** elscreen で開く

#+begin_src emacs-lisp
(defun elscreen-esh ()
  (interactive)
  (elscreen-create)
  (multi-eshell 1))
(global-set-key (kbd "C-c t b") 'elscreen-esh)
#+end_src

*** eshell-autojump
    
#+begin_src emacs-lisp
(use-package eshell-autojump)
#+end_src

*** eshell-z
    https://github.com/travisjeffery/eshell-z.el

#+begin_src emacs-lisp
(use-package eshell-z)
#+end_src

*** end of config

#+begin_src emacs-lisp
)
#+end_src

** shell-toggle
   現在ページでシェルを起動する.
   - https://github.com/knu/shell-toggle.el

#+begin_src emacs-lisp
(use-package shell-toggle
  :init
  (setq shell-toggle-launch-shell 'shell-toggle-eshell)
  :bind (("<C-M-return>" . shell-toggle-cd)) ;; バッファと eshell を toggle
  :config
  (setq shell-toggle-full-screen-window-only t))
;;(global-set-key [C-f1] 'shell-toggle-cd))
#+end_src

** shell-pop
   シェルをポップアップ.
   - [[http://d.hatena.ne.jp/kyagi/20090601/1243841415][Emacs でシェルを好きな時に呼び出す その 4 - 8tree にっき]]
   - https://github.com/kyagi/shell-pop-el

#+begin_src emacs-lisp
(use-package shell-pop
  :config
  (custom-set-variables
   '(shell-pop-default-directory "~/")
   '(shell-pop-shell-type
     (quote ("eshell" "*eshell*" (lambda nil (eshell shell-pop-term-shell)))))
   '(shell-pop-term-shell "/usr/bin/zsh")
   '(shell-pop-universal-key "M-p p")
   '(shell-pop-window-height 30)
   '(shell-pop-full-span t)
   '(shell-pop-window-position "bottom")))
#+end_src

** exec-path-from-shell
   環境変数 PATH を引き継ぐ.
   - [[https://github.com/purcell/exec-path-from-shell][purcell/exec-path-from-shell]]
   - http://sakito.jp/emacs/emacsshell.html#emacs

#+begin_src emacs-lisp
(use-package exec-path-from-shell
  :config
  (when (memq window-system '(mac ns))
    (exec-path-from-shell-initialize)))
#+end_src

** Emacs の起動フォルダを変更する.
   C-x C-f で開くディレクトリがデフォルト. 
   Windows だと, Emacs の起動ディレクトリになってしまう.
   
   default-directory を利用する

   #+begin_src emacs-lisp
(when windows-p
  (setq default-directory "C:/cygwin64/home/tsu-nera"))
#+end_src

   - [[http://stackoverflow.com/questions/60464/changing-the-default-folder-in-emacs][customization - Changing the default folder in Emacs - Stack Overflow]]
   - [[http://blog.cosscoss.biz/?p=477][Windows の Emacs (NTEmacs) で起動時ディレクトリを HOME ディレクトリに変更できない問題解決! | こすブ]]

** term-run
   interactive なターミナルを動かす.
   - https://github.com/10sr/term-run-el

#+begin_src emacs-lisp
(use-package term-run
  :config
  (defun term-run-alsamixer ()
    (interactive)
    (term-run-shell-command "alsamixer" nil))
  (defun term-run-feednix ()
    (interactive)
    (term-run "feednix" "*feednix*")))
#+end_src

** My Commands
** zlc
   zsh ライクに *Completion* をする
   - https://github.com/mooz/emacs-zlc

#+begin_src emacs-lisp
(use-package zlc
  :disabled t
  :config
  (zlc-mode t)

  (let ((map minibuffer-local-map))
  ;;; like menu select
  (define-key map (kbd "<down>")  'zlc-select-next-vertical)
  (define-key map (kbd "<up>")    'zlc-select-previous-vertical)
  (define-key map (kbd "<right>") 'zlc-select-next)
  (define-key map (kbd "<left>")  'zlc-select-previous)

  ;;; reset selection
  (define-key map (kbd "C-c") 'zlc-reset)))
#+end_src

*** slimlock
   Emacs から一時停止.

#+begin_src emacs-lisp
(defun lock ()
  (interactive)
  (shell-command "slimlock"))
#+end_src

* ファイラ
** dired

#+begin_src emacs-lisp
;; ディレクトリから表示
(setq ls-lisp-dirs-first t)
#+end_src

*** dired から open

#+begin_src emacs-lisp
(when linux-p
(defun dired-open-file ()
  "In dired, open the file named on this line."
  (interactive)
  (let* ((file (dired-get-filename nil t)))
    (message "Opening %s..." file)
    (call-process "xdg-open" nil 0 nil file)
    (message "Opening %s done" file)))

(add-hook
   'dired-mode-hook
   (lambda ()
     (define-key dired-mode-map [f6] 'dired-open-file))))
#+end_src

*** dired から term へ
    - [[http://oremacs.com/2015/01/10/dired-ansi-term/][dired and ansi-term: BFF · (or emacs]]

    eshell-cmd がないと怒られる.

#+begin_src emacs-lisp
;; (define-key dired-mode-map (kbd "'")
;;   (lambda ()
;;     (interactive)
;;     (eshell-cmd
;;      (format "cd %s"
;;              (expand-file-name
;;               default-directory)))))
#+end_src

*** 移動のたびに新規バッファをつくらない
    移動のたびにバッファをつくらないためには, i や a でバッファを開く.
    - [[http://stackoverflow.com/questions/1839313/how-do-i-stop-emacs-dired-mode-from-opening-so-many-buffers][file management - How do I stop emacs dired mode from opening so
      many buffers? - Stack Overflow]]

    or 

#+begin_src emacs-lisp
(put 'dired-find-alternate-file 'disabled nil)
#+end_src

  - [[http://macemacsjp.sourceforge.jp/index.php?EmacsDired][EmacsDired - MacEmacs]]

*** popwin で下から表示

#+begin_src emacs-lisp
(global-set-key (kbd "M-p d") 'dired-jump-other-window)
#+end_src

** joseph-single-dired
   バッファを複数作成しない.
   - https://github.com/jixiuf/joseph-single-dired

#+begin_src emacs-lisp
(use-package joseph-single-dired)
#+end_src

** Tramp
   リモートサーバに Emacs から乗り込む.

   こんな感じで乗り込む.
   - C-x C-f /ssh:username@hostname#portno:/path/to/your/directory

   Tramp で save 時に毎回パスワードが聞かれるので, おまじない.
   - [[http://stackoverflow.com/questions/840279/passwords-in-emacs-tramp-mode-editing][ssh - Passwords in Emacs tramp mode editing - Stack Overflow]]

#+begin_src emacs-lisp
(setq password-cache-expiry nil)
#+end_src

** dired-x
   dired の拡張.

#+begin_src emacs-lisp
(use-package dired-x)
#+end_src
** direx
   popup dired
   - https://github.com/m2ym/direx-el
   - http://cx4a.blogspot.jp/2011/12/popwineldirexel.html

   使っていないのと, open-junk-file とキーがかぶったので封印.
#+begin_src emacs-lisp
;; (use-package direx)
#+end_src
** dired-filetype-face
   dired で file-type にしたがって色付けをする.
   - https://github.com/jixiuf/dired-filetype-face
   - http://www.emacswiki.org/emacs/DiredFileTypeFaces

#+begin_src emacs-lisp
(use-package dired-filetype-face)
#+end_src

** dired-k
   highlight dired

#+begin_src emacs-lisp
(use-package dired-k
  :init
  (add-hook 'dired-initial-position-hook 'dired-k))
#+end_src

** neotree

#+begin_src emacs-lisp
(use-package neotree
  :config
  (global-set-key [f8] 'neotree-toggle))
#+end_src
   
* elscreen
  screen の Emacs バージョン. マルチプレクサ.
  - https://github.com/emacs-jp/elscreen
  - https://github.com/knu/elscreen

  オリジナルはメンテナンスされていないのかな?
  - http://www.morishima.net/~naoto/elscreen-ja/
  - http://nishikawasasaki.hatenablog.com/entry/20110313/1300031344

  #+begin_src emacs-lisp
(use-package elscreen
  :config
  (elscreen-start)
  
  ;; (setq elscreen-prefix-key "\C-o") ;; こっちだとダメだった
  (elscreen-set-prefix-key "\C-o")
  
  ;; タブの幅
  ;; (setq elscreen-display-tab 10)
  
  ; タブの左端の×を非表示
  (setq elscreen-tab-display-kill-screen nil)

  ;; <>を非表示
  (setq elscreen-tab-display-control nil)
  
  ;; emacsclient で新しいタブを開く
  ;; (use-package elscreen-server nil t)
  )
#+end_src

** colors

   #+begin_src emacs-lisp
;; (custom-set-faces ;; for monokai
;;  '(elscreen-tab-control-face ((t (:background "#1c1c1c" :foreground "#9e9e9e" :underline t))))
;;  '(elscreen-tab-current-screen-face ((t (:background "#444444" :foreground "#9e9e9e"))))
;;  '(elscreen-tab-other-screen-face ((t (:background "#262626" :foreground "#9e9e9e" :underline t)))))

;; それっぽい色をつける?? つけてくれないよ.
;;; (use-package elscreen-color-theme)
#+end_src

** screen の順番を手軽に変更
   ここから
   - [[http://qiita.com/fujimisakari/items/d7f1b904de11dcb018c3][Emacs - Elscreen に機能追加する - Qiita]]
   - https://gist.github.com/tsu-nera/44763febe82874785bf7

#+begin_src emacs-lisp
(use-package elscreen-interchange
  :bind (("M-<tab>" . elscreen-swap-next))
  ;; (("C-M-<right>" . elscreen-swap-next)
  ;; ("C-M-<left>" . elscreen-swap-previous))
  )
#+end_src

** TODO org-link を elscreen で開く
   いつか.
** elscreen-persistent
   - [[http://www.robario.com/2014/12/08][elscreen を永続化する elscreen-persist を書いた #Emacs @robario]]
   - [[http://rubikitch.com/2014/12/11/elscreen-persist/][elscreen のウィンドウ構成が windows.el ばりに再起動時に復元できるゾ! ]]

   revive というパッケージに依存している??

#+begin_src emacs-lisp
;;(use-package elscreen-persist
;;  :config
  ;; どうもこれを有効にすると Emacs が立ち上がらなくなるな...
  ;; (elscreen-persist-mode 1)
;;  )
#+end_src

*** 以下で操作
   - elscreen-persist-store
   - elscreen-persist-restore

** elscreen-wl
   waanderlust 用. syohex さんのやつ.
   - [[http://d.hatena.ne.jp/syohex/20130129/1359471993][elscreen-wl を fork しました Life is very short]]

   w をおすと別タブで開くので, ちょい便利.
   
 #+begin_src emacs-lisp
(when windows-p
  (use-package elscreen-wl))
#+end_src

 どこかで無限ループになっているな... 1 秒くらいここでかかっている.

#+begin_src text
Warning: Eager macro-expansion skipped due to cycle:
  … => (load "wl-e21.el") => (macroexpand-all …) => (macroexpand (eval-when-compile …)) => (load "wl-folder.el") => (macroexpand-all …) => (macroexpand (eval-when-compile …)) => (load "wl.el") => (load "wl-e21.el")
#+end_src

解決できないので封印.

** elscreen-dired
   dired で o をオスと別タブで開く.

   by wget https://raw.githubusercontent.com/knu/elscreen/master/elscreen-dired.el

#+begin_src emacs-lisp
(use-package elscreen-dired)
#+end_src

** Dired でカレントディレクトリを取得
  - [[http://d.hatena.ne.jp/syohex/20111026/1319606395][cde を改良 - Life is very short]]

#+begin_src emacs-lisp
;; .emacs 等設定ファイルに追加
;; Improve at 2013 年 9 月 14 日
(defun elscreen-get-current-directory (buf)
  (with-current-buffer buf
    (aif (buffer-file-name)
        (file-name-directory it)
      default-directory)))

(defun non-elscreen-current-directory ()
  (let* ((bufsinfo (cadr (cadr (current-frame-configuration))))
         (bufname-list (assoc-default 'buffer-list bufsinfo)))
    (loop for buf in bufname-list
          for file = (or (buffer-file-name buf)
                         (with-current-buffer buf
                           (when (eq major-mode 'dired-mode)
                             dired-directory)))
          when (buffer-file-name buf)
          return (file-name-directory it))))

(non-elscreen-current-directory)
;;(use-package cde)
#+end_src

* e2wm
  Emacs 用の window manager.

   - [[https://github.com/kiwanami/emacs-window-manager][kiwanami/emacs-window-manager]]
   - [[http://d.hatena.ne.jp/kiwanami/20100528/1275038929][広くなった画面を有効利用できる, Emacs 内 Window 管理ツール e2wm.el を作ってみた]]

   array を利用すると, windows のようなタブで画面切り替え.

   - [[http://aki2o.hatenablog.jp/entry/2014/08/19/Emacs%E3%81%A7%E3%83%90%E3%83%83%E3%83%95%E3%82%A1%E5%86%85%E5%AE%B9%E3%82%92%E7%9B%AE%E8%A6%96%E7%A2%BA%E8%AA%8D%E3%81%97%E3%81%A6%E7%9B%AE%E7%9A%84%E3%81%AE%E3%83%90%E3%83%83%E3%83%95%E3%82%A1%E3%81%AB][Emacs でバッファ内容を目視確認して目的のバッファに素早く切り替える - 死ぬまでの暇潰し]]

#+begin_src emacs-lisp
 (use-package e2wm
  :defer t
  :bind ("M-+" . e2wm:start-management))
#+end_src

>>>>>>> 823e3ffe11389b9ef1d28757fb10ef55c50369bc
