* Color
  色関係.

* Default
** Comment
#+begin_src emacs-lisp
(custom-set-faces
 '(font-lock-comment-delimiter-face ((t (:inherit font-lock-comment-face :foreground "gray80"))))
 '(font-lock-comment-face ((t (:foreground "gray80")))))
#+end_src

** 透過度
   alpha 変数に設定する. (set-frame-parameter nil 'alpha 80)

   今のテーマだと動かない. .
   - [[http://qiita.com/marcy_o/items/ba0d018a03381a964f24][cocoa emacs の透明度を変更する elisp - Qiita]]

#+begin_src emacs-lisp
(defun set-alpha (alpha-num)
  "set frame parameter 'alpha"
  (interactive "nAlpha: ")
  (set-frame-parameter nil 'alpha (cons alpha-num '(90))))
#+end_src

* Emacs Color Theme
  A collection of custom themes for Emacs.
  - https://github.com/owainlewis/emacs-color-themes

  会社だと, エラーするかもしれないため, マニュアルで入れることにした.

#+begin_src sh
$ git clone https://github.com/owainlewis/emacs-color-themes.git && cd emacs-color-themes && ./install.sh
#+end_src

  デフォルトで load される ?? 

#+begin_src emacs-lisp
(use-package emacs-color-themes :disabled t)
#+end_src

** Molokai
   Install  : https://raw2.github.com/hbin/molokai-theme/master/molokai-theme-kit.el
   現在は, fork してカスタマイズしたものをりようしている.

#+begin_src emacs-lisp
(add-to-list 'custom-theme-load-path "~/.emacs.d/el-get/repo/molokai-theme")
(use-package molokai-theme-kit
  :init
  (setq molokai-theme-kit t)
  (load-theme 'molokai t)
)
#+end_src

   自分のテーマにも, 以下のような設定で org-mode 対応できるらしい??
   - [[http://orgmode.org/worg/org-contrib/babel/examples/fontify-src-code-blocks.html][Pretty fontification of source code blocks]]
   -> mmm-mode で代用する.

** not used
*** tangotango
    org-mode に対応してるダークテーマ.
    - https://github.com/juba/color-theme-tangotango

    #+begin_src emacs-lisp
;;   (add-to-list 'custom-theme-load-path "~/.emacs.d/el-get/repo/color-theme-tangotango")
;;   (load-theme 'tangotango t)
    #+end_src

    tangotango と molokai をあわせると意外にいいかも??

*** Leuven-theme
    Emacs 24.4 に標準で入っているテーマ. org-mode との相性がとにかくイイ!
    - [[https://github.com/fniessen/emacs-leuven-theme][fniessen/emacs-leuven-theme]]

    #+begin_src emacs-lisp
;;   (load-theme 'leuven t)
    #+end_src
*** color-theme-molokai
    別の molokai
    - https://github.com/alloy-d/color-theme-molokai

 #+begin_src emacs-lisp
;; (add-to-list 'custom-theme-load-path "~/.emacs.d/el-get/repo/color-theme-molokai")
;; (load-theme 'molokai t)
 #+end_src

* rainbow-mode
  数字表記に色つけしてくれる 

#+begin_src emacs-lisp
(use-package rainbow-mode
  :init
  (add-hook 'css-mode-hook 'rainbow-mode)
  (add-hook 'html-mode-hook 'rainbow-mode)
  (add-hook 'emacs-lisp-mode-hook 'rainbow-mode)
  )
#+end_src

* rainbow-delimiters
   *注意* テーマ読み込みのあとに配置すること.

   かっこの深さに応じて色付けしてくれる.
   - https://github.com/Fanael/rainbow-delimiters

   かっこの強調をどきつくする. これはいいなぁ.
   - [[http://d.hatena.ne.jp/murase_syuka/20140815/1408061850][rainbow-delimiters.el の括弧色付けをデフォルトより強調する方法 - 会者定離で以降]]
   - [[http://yoo2080.wordpress.com/2013/12/21/small-rainbow-delimiters-tutorial/][Small rainbow-delimiters tutorial | Yoo Box]]

   #+begin_src emacs-lisp
(use-package rainbow-delimiters
  :init
  (add-hook 'emacs-lisp-mode-hook 'rainbow-delimiters-mode)
  (add-hook 'scheme-mode-hook 'rainbow-delimiters-mode)
  (add-hook 'lisp-mode-hook 'rainbow-delimiters-mode)
  :config
  ;; these setting should be placed after load-theme
  ;; using stronger colors
  (require 'cl-lib)
  (require 'color)

  ;; 関数にしないとうまくいかない...手動で有効に
  (defun rainbow-delimiters-using-stronger-colors ()
    (interactive)
  (cl-loop
   for index from 1 to rainbow-delimiters-max-face-count
   do
   (let ((face (intern (format "rainbow-delimiters-depth-%d-face" index))))
     (cl-callf color-saturate-name (face-foreground face) 100))))

  ;; making unmatched parens stand out more
  (set-face-attribute 'rainbow-delimiters-unmatched-face nil
		      :foreground 'unspecified
		      :inherit 'error
		      :strike-through t)
  )
#+end_src

* minimap
  Sublime Text のようなミニマップ.

#+begin_src emacs-lisp
(use-package minimap
  :disabled t
  :config
  (setq minimap-window-location 'right)
  (setq minimap-minimum-width 15)
  (global-set-key (kbd "C-c n") 'minimap-mode)

  ;; (when (display-graphic-p)
  ;;   (use-package minimap)
  ;;   ;; enable minimap
  ;;   (global-set-key (kbd "C-c n") 'minimap-toggle))
)
#+end_src

* pomodoro
  ここでやらないと, なぜかモードラインで表示されない.
  
#+begin_src emacs-lisp
;;(setq-default mode-line-format
;;   (cons '(:eval (pomodoro:propertize-mode-line))
;;    mode-line-format))
#+end_src

* ERC
  ダークからにデフォルトの色は合わない.
  - https://github.com/emacs-jp/replace-colorthemes/blob/master/blue-erc-theme.el
  - https://github.com/emacs-jp/replace-colorthemes/blob/master/dark-erc-theme.el

  #+begin_src emacs-lisp
(when windows-p 
 (add-to-list 'custom-theme-load-path "~/.emacs.d/elisp")
 (load-theme 'blue-erc t t)
 (enable-theme 'blue-erc)
 ;; (load-theme 'dark-erc t t)
 ;; (enable-theme 'dark-erc)
 )
 #+end_src

